jobs:
- name: scf-build
  plan:
  - aggregate:
    - get: scf
      params:
          submodules: none
    - get: capi-release
      trigger: true
    - get: eirini-release
    - get: ci-resources
  - task: scf-build
    privileged: true
    params:
      FISSILE_DOCKER_REGISTRY: ""
      FISSILE_DOCKER_USERNAME: ((dockerhub-user))
      FISSILE_DOCKER_PASSWORD: ((dockerhub-password))
      FISSILE_DOCKER_ORGANIZATION: "eirinicf"
    file: ci-resources/tasks/scf-build/task.yml
  - put: eirini-release
    params:
      repository: eirini-release-modified

resources:
- name: scf
  type: git
  source:
    uri: https://github.com/gdankov/scf.git
    branch: diego-come-back
    git_config:
    - name: submodule.fetchJobs
      value: 64
- name: capi-release
  type: git
  source:
    uri: https://github.com/JulzDiverse/capi-release.git
    branch: develop
- name: eirini-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/eirini-release.git
    branch: scf-latest
    private_key: ((eirini-release-private-key))
- name: ci-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci.git
    branch: master

