jobs:
- name: scf-build
  serial: true
  plan:
  - in_parallel:
    - get: scf-fork
    - get: eirini-release
    - get: ci-resources
  - task: scf-build
    privileged: true
    input_mapping:
      scf: scf-fork
    params:
      FISSILE_DOCKER_REGISTRY: ""
      DOCKER_USERNAME: ((dockerhub-user))
      DOCKER_PASSWORD: ((dockerhub-password))
      FISSILE_DOCKER_ORGANIZATION: "eirinicf"
      HELM_CHART_VERSION: 2.16.4
    file: ci-resources/tasks/scf-build/task.yml
    tags: [scf]
  - put: eirini-release
    params:
      merge: true
      repository: eirini-release-modified
- name: update-diego-chart-templates
  plan:
  - get: ci-resources
  - get: eirini-release
    passed: [scf-build]
    trigger: true
  - get: eirinifs-release
  - task: update-diego-templates
    file: ci-resources/tasks/update-diego-templates/task.yml
  - task: update-eirinifs-version
    input_mapping:
      eirini-release-modified: eirini-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/ci

      inputs:
      - name: ci-resources
      - name: eirini-release
      - name: eirinifs-release

      outputs:
      - name: eirini-release-modified

      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -euo pipefail
          eirinifs_version=$(cat eirinifs-release/tag)
          pushd eirini-release
          echo "global:" >> helm/cf/values.yaml
          echo "  rootfs_version: '$eirinifs_version'" >> helm/cf/values.yaml
          git add "helm/cf/values.yaml"
          git config --global user.email "eirini@cloudfoundry.org"
          git config --global user.name "Come-On Eirini"
          git commit --all --message "update eirinifs version"
          popd

          cp -r eirini-release/. eirini-release-modified/
  - put: eirini-release
    params:
      merge: true
      repository: eirini-release-modified

resources:
- name: scf-fork
  type: git
  icon: silverware-fork
  source:
    uri: https://github.com/eirini-forks/scf.git
    branch: eirini-scf-2.16.4
    git_config:
    - name: submodule.fetchJobs
      value: 64
- name: eirini-release
  type: git
  icon: git
  source:
    uri: git@github.com:cloudfoundry-incubator/eirini-release.git
    branch: scf-2.16.4
    private_key: ((eirini-release-private-key))
- name: ci-resources
  type: git
  icon: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci
    branch: master
- name: eirinifs-release
  check_every: 12h
  type: github-release
  icon: github-circle
  source:
    owner: cloudfoundry-incubator
    repository: eirinifs

