jobs:
- name: scf-build
  serial: true
  plan:
  - aggregate:
    - get: scf-fork
    - get: eirini-release
    - get: ci-resources
  - task: scf-build
    privileged: true
    input_mapping:
      scf: scf-fork
    params:
      FISSILE_DOCKER_REGISTRY: ""
      DOCKER_USERNAME: ((dockerhub-user))
      DOCKER_PASSWORD: ((dockerhub-password))
      FISSILE_DOCKER_ORGANIZATION: "eirinicf"
      HELM_CHART_VERSION: 2.16.4
    file: ci-resources/tasks/scf-build/task.yml
    tags: [scf]
  - put: eirini-release
    params:
      merge: true
      repository: eirini-release-modified
- name: update-diego-chart-templates
  plan:
  - get: ci-resources
  - get: eirini-release
    passed: [scf-build]
    trigger: true
  - task: update-diego-templates
    file: ci-resources/tasks/update-diego-templates/task.yml
  - put: eirini-release
    params:
      merge: true
      repository: eirini-release-modified

resources:
- name: scf-fork
  type: git
  source:
    uri: https://github.com/eirini-forks/scf.git
    branch: eirini-scf-2.16.4
    git_config:
    - name: submodule.fetchJobs
      value: 64
- name: eirini-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/eirini-release.git
    branch: scf-2.16.4
    private_key: ((eirini-release-private-key))
- name: ci-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci
    branch: master

