jobs:
- name: update-docker-images
  plan:
  - get: ci-resources
  - get: eirini-release
    trigger: true
  - task: update docker image
    privileged: true
    params:
      DOCKER_HUB_USER: ((docker_hub_user))
      DOCKER_HUB_PASSWORD: ((docker_hub_password))
      TAG: latest
    file: ci-resources/tasks/create-docker-images.yml

resources:
- name: eirini-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: master

- name: ci-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci.git
    branch: master
