jobs:
- name: update-docker-images
  plan:
  - get: ci-resources
  - get: eirini-release
    trigger: true
  - task: update docker image
    privileged: true
    params:
      DOCKER_HUB_USER: ((docker_hub_user))
      DOCKER_HUB_PASSWORD: ((docker_hub_password))
      TAG: latest
    file: ci-resources/tasks/create-docker-images/task.yml
- name: update-eirini-ci-image
  plan:
  - get: golang-image
    trigger: true
  - get: eirini-ci-image-source
    trigger: true
  - put: eirini-ci-image
    params: {build: eirini-ci-image-source}

resources:
- name: eirini-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: master

- name: ci-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci.git
    branch: master

- name: eirini-ci-image-source
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci.git
    branch: master
    path: Dockerfile

- name: eirini-ci-image
  type: docker-image
  source:
    repository: eirini/ci
    username: ((docker_hub_user))
    password: ((docker_hub_password))

- name: golang-image
  type: docker-image
  source:
    repository: golang
