platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

inputs:
  - name: ci-resources
  - name: cluster-state

outputs:
  - name: state-modified

params:
  CLUSTER_NAME:

run:
  path: ci-resources/tasks/clean-up-cluster-config/task.sh
