platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
  - name: ci-resources
  - name: cluster-state
  - name: kube

run:
  path: ci-resources/tasks/install-helm-dependencies/task.sh
