---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
- name: kube
- name: ci-resources
- name: cluster-state
- name: kubecf
- name: eirini-release

params:
  CLUSTER_NAME:
  CF_OPERATOR_CHART_URL:

run:
  path: ci-resources/tasks/kubecf/deploy/task.sh
