resources:
- name: eirini-scf-release
  type: github-release
  icon: rocket
  source:
    owner: cloudfoundry-incubator
    repository: eirini-release
    access_token: ((github-access-token))
    drafts: true
- name: eirini-release-version
  type: semver
  icon: check-decagram
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: master
    file: release-version
    private_key: ((github-private-key))
    initial_version: 0.1.0
- name: gh-pages-pr
  type: git
  icon: git
  source:
    uri: git@github.com:cloudfoundry-incubator/eirini-release.git
    branch: gh-pages-pr
    private_key: ((eirini-release-repo-key))
- name: eirini
  type: git
  icon: git
  source:
    uri: git@github.com:cloudfoundry-incubator/eirini
    branch: master
    private_key: ((eirini-repo-key))
- name: staging
  type: git
  icon: git
  source:
    uri: git@github.com:cloudfoundry-incubator/eirini-staging
    branch: master
    private_key: ((eirini-staging-repo-key))
groups:
- name: publish-release
  jobs:
  - publish-release
  - bump-minor-version
  - bump-major-version

jobs:
- ((merge))
- name: bump-major-version
  plan:
  - get: eirini-release-version
    params:
      bump: major
  - put: eirini-release-version
    params:
      file: eirini-release-version/version
- name: bump-minor-version
  plan:
  - get: eirini-release-version
    passed:
    - publish-release
    trigger: true
    params:
      bump: minor
  - put: eirini-release-version
    params:
      file: eirini-release-version/version
- name: publish-release
  plan:
  - get: ci-resources
  - get: gh-pages-pr
  - task: check-for-pending-release
    params:
     GITHUB_TOKEN: ((github-access-token))
    file: ci-resources/tasks/check-for-pending-release/task.yml
  - get: state
  - get: eirini-release
    passed:
    - run-smoke-tests-acceptance
  - get: eirini-release-version
  - task: create-release
    params:
      CLUSTER_NAME: (( grab meta.cluster-name ))
    file: ci-resources/tasks/create-release/task.yml
  - task: update-helm-index
    file: ci-resources/tasks/update-helm-repo/task.yml
  - put: eirini-scf-release
    params:
      name: eirini-release-version/version
      tag: eirini-release-version/version
      tag_prefix: v
      globs:
      - release-output/eirini*.tgz
  - put: gh-pages-pr
    params:
      repository: gh-pages-updated
  - task: create-github-pr
    params:
     GITHUB_TOKEN: ((github-access-token))
    file: ci-resources/tasks/create-github-pr/task.yml
  - get: eirini
  - task: checkout-eirini-sha
    privileged: true
    file: ci-resources/tasks/checkout-sha-by-image/task.yml
    params:
      VERSION_FILE: opi
      IMAGE_NAME: docker.io/eirini/opi
    input_mapping:
      repository: eirini
    output_mapping:
      repository-modified: eirini-modified
  - put: eirini
    params:
      repository: eirini-modified
      only_tag: true
      tag: eirini-release-version/version

  - get: staging
  - task: checkout-staging-sha
    privileged: true
    file: ci-resources/tasks/checkout-sha-by-image/task.yml
    params:
      VERSION_FILE: staging-downloader
      IMAGE_NAME: docker.io/eirini/recipe-downloader
    input_mapping:
      repository: staging
    output_mapping:
      repository-modified: staging-modified
  - put: staging
    params:
      repository: staging-modified
      only_tag: true
      tag: eirini-release-version/version

