resources:
- name: eirini-scf-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: eirini-release
    access_token: ((github-access-token))
    drafts: true
- name: eirini-release-version
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: master
    file: release-version
    private_key: ((github-private-key))
    initial_version: 0.1.0
- name: gh-pages-pr
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/eirini-release.git
    branch: gh-pages-pr
    private_key: ((eirini-release-repo-key))

groups:
- name: publish-release
  jobs:
  - publish-release

jobs:
- ((merge))
- name: publish-release
  plan:
  - get: ci-resources
  - get: gh-pages-pr
  - task: check-for-pending-release
    params:
     GITHUB_TOKEN: ((github-access-token))
    file: ci-resources/tasks/check-for-pending-release/task.yml
  - get: state
  - get: eirini-release
    passed:
    - run-smoke-tests-acceptance
  - get: eirini-release-version
    params:
      bump: minor
  - task: create-release
    params:
      CLUSTER_NAME: (( grab meta.cluster-name ))
    file: ci-resources/tasks/create-release/task.yml
  - task: update-helm-index
    file: ci-resources/tasks/update-helm-repo/task.yml
  - put: eirini-scf-release
    params:
      name: eirini-release-version/version
      tag: eirini-release-version/version
      tag_prefix: v
      globs:
      - release-output/eirini*.tgz
  - put: gh-pages-pr
    params:
      repository: gh-pages-updated
  - task: create-github-pr
    params:
     GITHUB_TOKEN: ((github-access-token))
    file: ci-resources/tasks/create-github-pr/task.yml
  - put: eirini-release-version
    params:
      file: eirini-release-version/version
