resources:
- name: eirini-scf-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: eirini-release
    access_token: ((github-access-token))
    drafts: true
- name: release-version
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: master
    file: release-version
    private_key: ((github-private-key))
    initial_version: 0.1.0
- name: gh-pages
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/eirini-release.git
    branch: gh-pages
    private_key: ((eirini-release-repo-key))

groups:
- name: publish-release
  jobs:
  - publish-release

jobs:
- ((merge))
- name: publish-release
  plan:
  - get: ci-resources
  - get: gh-pages
  - get: state
  - get: eirini-release
    params:
      submodules: all
  - get: release-version
    params:
      bump: minor
  - task: create-release-images
    privileged: true
    params:
      DOCKER_HUB_USER: ((dockerhub-user))
      DOCKER_HUB_PASSWORD: ((dockerhub-password))
      CLUSTER_NAME: ((cluster-name))
    file: ci-resources/tasks/create-release-images/task.yml
  - task: create-release
    params:
      CLUSTER_NAME: ((cluster-name))
    file: ci-resources/tasks/create-release/task.yml
  - task: update-helm-index
    file: ci-resources/tasks/update-helm-repo/task.yml
  - put: release-version
    params:
      file: release-version/version
  - put: eirini-scf-release
    params:
      name: release-version/version
      tag: release-version/version
      tag_prefix: v
      globs:
      - release-output/eirini*.tgz
  - put: gh-pages
    params:
       repository: gh-pages-updated
