groups:
- (( defer merge ))
- name: all
  jobs:
  - (( defer prepend ))
  - cleanup-blobstore
jobs:
- name: cleanup-blobstore
  plan:
  - get: ci-resources
  - get: sunday-morning
    trigger: true
  - task: cleanup-blobstore
    file: ci-resources/tasks/cleanup-blobstore/task.yml
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: (( grab meta.cluster-name ))
resources:
- name: sunday-morning
  type: time
  source:
    days: [Sunday]
    start: 10:00 AM
    stop: 11:00 AM
