platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
  - name: kube
  - name: ingress
  - name: ci-resources
  - name: cluster-state

outputs:
  - name: state-modified

params:
  IBMCLOUD_ACCOUNT:
  IBMCLOUD_USER:
  IBMCLOUD_PASSWORD:
  CLUSTER_NAME:
  STORAGE_CLASS:

run:
  path: ci-resources/tasks/create-values-file/task.sh
