---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
  - name: ci-resources
  - name: kube

run:
  path: ci-resources/tasks/verify-no-diego/task.sh
