---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
  - name: ci-resources
  - name: kube
  - name: state

params:
  IBMCLOUD_ACCOUNT:
  IBMCLOUD_USER:
  IBMCLOUD_PASSWORD:
  COMPONENT:
  CLUSTER_NAME:
  HELM_CHART:

run:
  path: ci-resources/tasks/verify-no-diego/task.sh
