---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golangci/golangci-lint
    tag: v1.21

inputs:
- name: ci-resources
- name: eirini

run:
  path: ci-resources/tasks/run-static-checks/task.sh
