---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud
    tag: helm3

inputs:
- name: kube
- name: ci-resources

run:
  path: ci-resources/tasks/kubecf/delete/task.sh
