jobs:
- name: deploy-cube-release
  plan:
  - get: ci-resources
  - get: cube-release
    trigger: true
  - get: cf-deployment
    trigger: true
  - get: bosh-lite-softlayer
  - task: deploy
    privileged: true
    params:
      BOSH_DIRECTOR: ((bosh_director))
      BOSH_CLIENT: ((bosh_client))
      BOSH_CLIENT_SECRET: ((bosh_client_secret))
      BOSH_CRT: ((bosh_crt))
      DIRECTOR_IP: ((director_ip))
      CC_API: ((cc_api))
      KUBE_CONF: ((cube_conf))
    file: ci-resources/tasks/deploy-cube-release.yml

resources:
- name: ci-resources
  type: git
  source:
    uri: https://github.com/JulzDiverse/cube-release-ci.git
    branch: master

- name: cube-release
  type: git
  source:
    uri: https://github.com/andrew-edgar/cube-release.git
    branch: master

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment.git
    branch: master

- name: bosh-lite-softlayer
  type: git
  source:
    uri: http://github.com/JulzDiverse/bosh-lite-softlayer.git
    branch: master
