---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

inputs:
  - name: ci-resources
  - name: eirinidotcf
  - name: eirini-private-config
  - name: db-conf

run:
  path: ci-resources/tasks/deploy-eirinidotcf/task.sh
