---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

inputs:
- name: ci-resources
- name: eirini

run:
  path: ci-resources/tasks/update-fluentd-image/task.sh
