jobs:
- name: bump-minor-version
  on_failure: (( grab slack-notification.on_failure ))
  plan:
  - get: eirini-release-version
    params:
      bump: minor
    passed:
    - publish-release
    trigger: true
  - params:
      file: eirini-release-version/version
    put: eirini-release-version
