jobs:
- name: bump-cflinuxfs3
  plan:
  - in_parallel:
    - get: eirinifs
    - get: cflinuxfs3-release
      trigger: true
  - task: bump-eirinifs
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/ci
      inputs:
      - name: eirinifs
      - name: cflinuxfs3-release
      outputs:
      - name: eirinifs-modified
      run:
        path: bash
        args:
        - -c
        - (( file "../../inline-tasks/bump-eirinifs.sh" ))
  - put: eirinifs
    params:
      merge: true
      repository: eirinifs-modified
  on_failure: (( grab slack-notification.on_failure ))
