jobs:
- name: bump-major-version
  on_failure: (( grab slack-notification.on_failure ))
  plan:
  - get: eirini-release-version
    params:
      bump: major
  - params:
      file: eirini-release-version/version
    put: eirini-release-version
