jobs:
- name: bump-cluster-k8s-version
  on_failure: (( grab slack-notification.on_failure ))
  plan:
  - get: ci-resources
  - config:
      container_limits: {}
      image_resource:
        source:
          repository: eirini/ibmcloud
        type: docker-image
      inputs:
      - name: ci-resources
      platform: linux
      run:
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/bump-version-acceptance.sh" ))
        path: /usr/bin/env
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      IBMCLOUD_USER: ((ibmcloud-user))
    task: bump-k8s-version
