jobs:
- name: check-shell
  on_failure: (( grab slack-notification.on_failure ))
  plan:
  - get: ci-resources
    trigger: true
  - task: run-shellcheck
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: koalaman/shellcheck-alpine
          username: (( grab config.dockerhub.user ))
          password: (( grab config.dockerhub.password ))
          tag: stable
      inputs:
      - name: ci-resources
      run:
        path: /usr/bin/env
        args:
        - sh
        - -c
        - (( file "../../inline-tasks/check-shell.sh" ))
