jobs:
- name: cleanup-blobstore
  on_failure: (( grab slack-notification.on_failure ))
  plan:
  - get: ci-resources
  - get: sunday-morning
    trigger: true
  - task: download-kubeconfig
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/ibmcloud
      inputs:
      - name: ci-resources
      outputs:
      - name: kube
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/download-kubeconfig.sh" ))
    params:
      CLUSTER_NAME: acceptance
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      IBMCLOUD_USER: ((ibmcloud-user))
  - task: cleanup-blobstore
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/ibmcloud
      inputs:
      - name: kube
      - name: ci-resources
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/cleanup-blobstore.sh" ))
