jobs:
- name: create-go-docker-images
  on_failure: (( grab slack-notification.on_failure ))
  plan:
  - get: eirini
    passed:
    - run-integration-tests
    trigger: true
  - task: make-docker-build-args
    input_mapping:
        repository: eirini
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/ci
          username: (( grab config.dockerhub.user ))
          password: (( grab config.dockerhub.password ))
      inputs:
      - name: repository
      outputs:
      - name: docker-build-args
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/make-docker-build-args.sh" ))
  - in_parallel:
      limit: 3
      steps:
        - do:
          - task: build-opi
            privileged: true
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: vito/oci-build-task
              inputs:
              - name: eirini
              - name: docker-build-args
              outputs:
              - name: image
              caches:
              - path: cache
              params:
                CONTEXT: eirini
                BUILD_ARGS_FILE: docker-build-args/args
                DOCKERFILE: eirini/docker/opi/Dockerfile
              run:
                path: build
            output_mapping: {image: opi-image}
          - put: opi-image
            params: {image: opi-image/image.tar}
        - do:
          - task: build-route-collector
            privileged: true
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: vito/oci-build-task
              inputs:
              - name: eirini
              - name: docker-build-args
              outputs:
              - name: image
              caches:
              - path: cache
              params:
                CONTEXT: eirini
                BUILD_ARGS_FILE: docker-build-args/args
                DOCKERFILE: eirini/docker/route-collector/Dockerfile
              run:
                path: build
            output_mapping: {image: route-collector-image}
          - put: route-collector-image
            params: {image: route-collector-image/image.tar}
        - do:
          - task: build-route-pod-informer
            privileged: true
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: vito/oci-build-task
              inputs:
              - name: eirini
              - name: docker-build-args
              outputs:
              - name: image
              caches:
              - path: cache
              params:
                CONTEXT: eirini
                BUILD_ARGS_FILE: docker-build-args/args
                DOCKERFILE: eirini/docker/route-pod-informer/Dockerfile
              run:
                path: build
            output_mapping: {image: route-pod-informer-image}
          - put: route-pod-informer-image
            params: {image: route-pod-informer-image/image.tar}
        - do:
          - task: build-metrics-collector
            privileged: true
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: vito/oci-build-task
              inputs:
              - name: eirini
              - name: docker-build-args
              outputs:
              - name: image
              caches:
              - path: cache
              params:
                CONTEXT: eirini
                BUILD_ARGS_FILE: docker-build-args/args
                DOCKERFILE: eirini/docker/metrics-collector/Dockerfile
              run:
                path: build
            output_mapping: {image: metrics-collector-image}
          - put: metrics-collector-image
            params: {image: metrics-collector-image/image.tar}
        - do:
          - task: build-event-reporter
            privileged: true
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: vito/oci-build-task
              inputs:
              - name: eirini
              - name: docker-build-args
              outputs:
              - name: image
              caches:
              - path: cache
              params:
                CONTEXT: eirini
                BUILD_ARGS_FILE: docker-build-args/args
                DOCKERFILE: eirini/docker/event-reporter/Dockerfile
              run:
                path: build
            output_mapping: {image: event-reporter-image}
          - put: event-reporter-image
            params: {image: event-reporter-image/image.tar}
        - do:
          - task: build-task-reporter
            privileged: true
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: vito/oci-build-task
              inputs:
              - name: eirini
              - name: docker-build-args
              outputs:
              - name: image
              caches:
              - path: cache
              params:
                CONTEXT: eirini
                BUILD_ARGS_FILE: docker-build-args/args
                DOCKERFILE: eirini/docker/task-reporter/Dockerfile
              run:
                path: build
            output_mapping: {image: task-reporter-image}
          - put: task-reporter-image
            params: {image: task-reporter-image/image.tar}
        - do:
          - task: build-route-statefulset-informer
            privileged: true
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: vito/oci-build-task
              inputs:
              - name: eirini
              - name: docker-build-args
              outputs:
              - name: image
              caches:
              - path: cache
              params:
                CONTEXT: eirini
                BUILD_ARGS_FILE: docker-build-args/args
                DOCKERFILE: eirini/docker/route-statefulset-informer/Dockerfile
              run:
                path: build
            output_mapping: {image: route-statefulset-informer-image}
          - put: route-statefulset-informer-image
            params: {image: route-statefulset-informer-image/image.tar}
        - do:
          - task: build-eirini-controller
            privileged: true
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: vito/oci-build-task
              inputs:
              - name: eirini
              - name: docker-build-args
              outputs:
              - name: image
              caches:
              - path: cache
              params:
                CONTEXT: eirini
                BUILD_ARGS_FILE: docker-build-args/args
                DOCKERFILE: eirini/docker/eirini-controller/Dockerfile
              run:
                path: build
            output_mapping: {image: eirini-controller-image}
          - put: eirini-controller-image
            params: {image: eirini-controller-image/image.tar}
        - do:
          - task: build-instance-index-env-injector
            privileged: true
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: vito/oci-build-task
              inputs:
              - name: eirini
              - name: docker-build-args
              outputs:
              - name: image
              caches:
              - path: cache
              params:
                CONTEXT: eirini
                BUILD_ARGS_FILE: docker-build-args/args
                DOCKERFILE: eirini/docker/instance-index-env-injector/Dockerfile
              run:
                path: build
            output_mapping: {image: instance-index-env-injector-image}
          - put: instance-index-env-injector-image
            params: {image: instance-index-env-injector-image/image.tar}
