jobs:
- name: create-go-docker-images
  plan:
  - in_parallel:
      limit: 5
      steps:
      - get: eirini
        passed:
        - run-tests
        trigger: true
  - task: make-docker-build-args
    input_mapping:
        repository: eirini
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/ci
      inputs:
      - name: repository
      outputs:
      - name:  docker-build-args
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/make-docker-build-args.sh" ))
  - in_parallel:
      limit: 5
      steps:
      - params:
          build: eirini
          build_args_file: docker-build-args/args.json
          dockerfile: eirini/docker/opi/Dockerfile
        put: docker-opi
      - params:
          build: eirini
          build_args_file: docker-build-args/args.json
          dockerfile: eirini/docker/bits-waiter/Dockerfile
        put: docker-bits-waiter
      - params:
          build: eirini
          build_args_file: docker-build-args/args.json
          dockerfile: eirini/docker/rootfs-patcher/Dockerfile
        put: docker-rootfs-patcher
      - params:
          build: eirini
          build_args_file: docker-build-args/args.json
          dockerfile: eirini/docker/route-collector/Dockerfile
        put: docker-route-collector
      - params:
          build: eirini
          build_args_file: docker-build-args/args.json
          dockerfile: eirini/docker/route-pod-informer/Dockerfile
        put: docker-route-pod-informer
      - params:
          build: eirini
          build_args_file: docker-build-args/args.json
          dockerfile: eirini/docker/metrics-collector/Dockerfile
        put: docker-metrics-collector
      - params:
          build: eirini
          build_args_file: docker-build-args/args.json
          dockerfile: eirini/docker/event-reporter/Dockerfile
        put: docker-event-reporter
      - params:
          build: eirini
          build_args_file: docker-build-args/args.json
          dockerfile: eirini/docker/staging-reporter/Dockerfile
        put: docker-staging-reporter
      - put: docker-task-reporter
        params:
          build: eirini
          build_args_file: docker-build-args/args.json
          dockerfile: eirini/docker/task-reporter/Dockerfile
      - params:
          build: eirini
          build_args_file: docker-build-args/args.json
          dockerfile: eirini/docker/route-statefulset-informer/Dockerfile
        put: docker-route-statefulset-informer
      - put: docker-lrp-controller
        params:
          build: eirini
          build_args_file: docker-build-args/args.json
          dockerfile: eirini/docker/lrp-controller/Dockerfile
  on_failure: (( grab slack-notification.on_failure ))
