jobs:
- name: create-go-docker-images
  plan:
  - get: eirini
    passed:
    - run-integration-tests
    trigger: true
  - task: make-docker-build-args
    input_mapping:
        repository: eirini
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/ci
          username: (( grab config.dockerhub.user ))
          password: (( grab config.dockerhub.password ))
      inputs:
      - name: repository
      outputs:
      - name:  docker-build-args
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/make-docker-build-args.sh" ))
  - in_parallel:
      limit: 1
      steps:
      - do:
        - task: build
          privileged: true
          output_mapping:
            image: opi-image
          config:
            caches:
            - path: cache
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: vito/oci-build-task
            inputs:
            - name: eirini
              path: .
            - name: docker-build-args
            outputs:
            - name: image
            run:
              path: build
            params:
              BUILD_ARGS_FILE: docker-build-args/args
              DOCKERFILE: docker/opi/Dockerfile
        - put: docker-opi
          params: {image: opi-image/image.tar}

      - do:
        - task: build
          privileged: true
          output_mapping:
            image: route-collector-image
          config:
            caches:
            - path: cache
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: vito/oci-build-task
            inputs:
            - name: eirini
              path: .
            - name: docker-build-args
            outputs:
            - name: image
            run:
              path: build
            params:
              BUILD_ARGS_FILE: docker-build-args/args
              DOCKERFILE: docker/route-collector/Dockerfile
        - put: docker-route-collector
          params: {image: route-collector-image/image.tar}

      - do:
        - task: build
          privileged: true
          output_mapping:
            image: route-pod-informer-image
          config:
            caches:
            - path: cache
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: vito/oci-build-task
            inputs:
            - name: eirini
              path: .
            - name: docker-build-args
            outputs:
            - name: image
            run:
              path: build
            params:
              BUILD_ARGS_FILE: docker-build-args/args
              DOCKERFILE: docker/route-pod-informer/Dockerfile
        - put: docker-route-pod-informer
          params: {image: route-pod-informer-image/image.tar}

      - do:
        - task: build
          privileged: true
          output_mapping:
            image: metrics-collector-image
          config:
            caches:
            - path: cache
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: vito/oci-build-task
            inputs:
            - name: eirini
              path: .
            - name: docker-build-args
            outputs:
            - name: image
            run:
              path: build
            params:
              BUILD_ARGS_FILE: docker-build-args/args
              DOCKERFILE: docker/metrics-collector/Dockerfile
        - put: docker-metrics-collector
          params: {image: metrics-collector-image/image.tar}

      - do:
        - task: build
          privileged: true
          output_mapping:
            image: event-reporter-image
          config:
            caches:
            - path: cache
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: vito/oci-build-task
            inputs:
            - name: eirini
              path: .
            - name: docker-build-args
            outputs:
            - name: image
            run:
              path: build
            params:
              BUILD_ARGS_FILE: docker-build-args/args
              DOCKERFILE: docker/event-reporter/Dockerfile
        - put: docker-event-reporter
          params: {image: event-reporter-image/image.tar}

      - do:
        - task: build
          privileged: true
          output_mapping:
            image: staging-reporter-image
          config:
            caches:
            - path: cache
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: vito/oci-build-task
            inputs:
            - name: eirini
              path: .
            - name: docker-build-args
            outputs:
            - name: image
            run:
              path: build
            params:
              BUILD_ARGS_FILE: docker-build-args/args
              DOCKERFILE: docker/staging-reporter/Dockerfile
        - put: docker-staging-reporter
          params: {image: staging-reporter-image/image.tar}

      - do:
        - task: build
          privileged: true
          output_mapping:
            image: task-reporter-image
          config:
            caches:
            - path: cache
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: vito/oci-build-task
            inputs:
            - name: eirini
              path: .
            - name: docker-build-args
            outputs:
            - name: image
            run:
              path: build
            params:
              BUILD_ARGS_FILE: docker-build-args/args
              DOCKERFILE: docker/task-reporter/Dockerfile
        - put: docker-task-reporter
          params: {image: task-reporter-image/image.tar}

      - do:
        - task: build
          privileged: true
          output_mapping:
            image: route-statefulset-informer-image
          config:
            caches:
            - path: cache
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: vito/oci-build-task
            inputs:
            - name: eirini
              path: .
            - name: docker-build-args
            outputs:
            - name: image
            run:
              path: build
            params:
              BUILD_ARGS_FILE: docker-build-args/args
              DOCKERFILE: docker/route-statefulset-informer/Dockerfile
        - put: docker-route-statefulset-informer
          params: {image: route-statefulset-informer-image/image.tar}

      - do:
        - task: build
          privileged: true
          output_mapping:
            image: eirini-controller-image
          config:
            caches:
            - path: cache
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: vito/oci-build-task
            inputs:
            - name: eirini
              path: .
            - name: docker-build-args
            outputs:
            - name: image
            run:
              path: build
            params:
              BUILD_ARGS_FILE: docker-build-args/args
              DOCKERFILE: docker/eirini-controller/Dockerfile
        - put: docker-eirini-controller
          params: {image: eirini-controller-image/image.tar}

      - do:
        - task: build
          privileged: true
          output_mapping:
            image: instance-index-env-injector-image
          config:
            caches:
            - path: cache
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: vito/oci-build-task
            inputs:
            - name: eirini
              path: .
            - name: docker-build-args
            outputs:
            - name: image
            run:
              path: build
            params:
              BUILD_ARGS_FILE: docker-build-args/args
              DOCKERFILE: docker/instance-index-env-injector/Dockerfile
        - put: docker-instance-index-env-injector
          params: {image: instance-index-env-injector-image/image.tar}

  on_failure: (( grab slack-notification.on_failure ))
