jobs:
- name: create-cluster-((world-name))
  plan:
  - get: ci-resources
  - get: cluster-state
    trigger: true
    passed: [delete-cluster-((world-name))]
  - task: create-kubernetes-cluster
    file: ci-resources/tasks/gcp-create-cluster/task.yml
    params:
      GCP_SERVICE_ACCOUNT_JSON: ((gcp-service-account-json))
      CLUSTER_NAME: ((world-name))
      WORKER_COUNT: ((worker_count))
  - put: cluster-((world-name))-staging-event-created
    params:
      bump: major
