jobs:
- name: create-secret-smuggler-docker-image
  plan:
  - in_parallel:
      steps:
      - get: ci-resources
      - get: eirini-secret-smuggler
        trigger: true
  - file: ci-resources/tasks/make-docker-build-args/task.yml
    input_mapping:
      repository: eirini-secret-smuggler
    task: make-docker-build-args
  - params:
      build: eirini-secret-smuggler/docker/registry/certs/smuggler
      build_args_file: docker-build-args/args.json
    put: docker-secret-smuggler
  on_failure: (( grab slack-notification.on_failure ))
