jobs:
- name: (( concat "create-cluster-" cluster.name ))
  plan:
  - get: ci-resources
  - get: cluster-state
    trigger: true
    passed: [(( concat "delete-cluster-" cluster.name ))]
  - task: create-kubernetes-cluster
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/gcloud
      inputs:
        - name: ci-resources
      params:
        GCP_SERVICE_ACCOUNT_JSON: ((gcp-service-account-json))
        CLUSTER_NAME: (( grab cluster.name ))
        WORKER_COUNT: ((worker_count))
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/gcp-create-cluster.sh" ))
  - put: (( concat "cluster-" cluster.name "-staging-event-created" ))
    params:
      bump: major
