jobs:
- name: create-secret-smuggler-docker-image
  plan:
  - in_parallel:
      steps:
      - get: eirini-secret-smuggler
        trigger: true
  - task: make-docker-build-args
    input_mapping:
        repository: eirini-secret-smuggler
    config:
       platform: linux
       image_resource:
         type: docker-image
         source:
           repository: eirini/ci
       inputs:
       - name: repository
       outputs:
       - name:  docker-build-args
       run:
         path: /usr/bin/env
         args:
         - bash
         - -c
         - (( file "../../inline-tasks/make-docker-build-args.sh" ))
  - params:
      build: eirini-secret-smuggler/docker/registry/certs/smuggler
      build_args_file: docker-build-args/args.json
    put: docker-secret-smuggler
  on_failure: (( grab slack-notification.on_failure ))
