jobs:
- name: (( concat "delete-cluster-" config.cluster.name ))
  plan:
  - get: ci-resources
  - task: delete-kubernetes-cluster
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/gcloud
      inputs:
        - name: ci-resources
      params:
        CLUSTER_NAME: (( grab config.cluster.name ))
        GCP_SERVICE_ACCOUNT_JSON: (( grab config.gcp.service-account-json ))
        WORKER_COUNT: (( grab config.cluster.worker-count))
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/gcp-delete-cluster.sh" ))
    params:
      CLUSTER_NAME: (( grab config.cluster.name ))
      GCP_SERVICE_ACCOUNT_JSON: (( grab config.gcp.service-account-json ))
      WORKER_COUNT: (( grab config.cluster.worker-count))
  - get: cluster-state
  - task: delete-values-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/ci
      inputs:
        - name: cluster-state
      outputs:
        - name: state-modified
      params:
        CLUSTER_NAME: (( grab config.cluster.name ))
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/clean-up-cluster-config.sh" ))
  - put: cluster-state
    params:
      merge: true
      repository: state-modified
