jobs:
- name: fast-forward-release
  plan:
  - get: eirini-release
    trigger: true
    passed:
    - unlock-ci
  - get: eirini-release-master
  - put: eirini-release-master
    params:
      repository: eirini-release
