jobs:
- name: fast-forward-release
  plan:
  - get: eirini-release
    trigger: true
    passed:
    - run-integration-tests
    - run-eats-tests-((gcp-cluster-name))
  - get: eirini-release-master
  - put: eirini-release-master
    params:
      repository: eirini-release
