jobs:
- name: format-shell
  on_failure: (( grab slack-notification.on_failure ))
  plan:
  - get: ci-resources
    trigger: true
  - task: run-shfmt
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/ci
      inputs:
      - name: ci-resources
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/format-shell.sh" ))
