jobs:
- name: prepare-cluster-((world-name))
  plan:
  - in_parallel:
    - get: ci-resources
    - get: cluster-((world-name))-staging-event-created
      trigger: true
      passed: [create-cluster-((world-name))]
    - get: cluster-state
  - task: download-kubeconfig
    params:
      CLUSTER_NAME: ((world-name))
      GCP_REGION: ((gcp-region))
      GCP_SERVICE_ACCOUNT_JSON: ((gcp-service-account-json))
      GCP_ZONE: ((gcp-zone))
    config:
      image_resource:
        source:
          repository: google/cloud-sdk
        type: docker-image
      platform: linux
      inputs:
        - name: ci-resources
      outputs:
        - name: kube
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/gcp-download-kubeconfig.sh" ))
  - task: create-cluster-config
    config:
     platform: linux
     image_resource:
       type: docker-image
       source:
         repository: eirini/ci
     inputs:
       - name: ci-resources
       - name: cluster-state
     outputs:
       - name: state-modified
     params:
       CLUSTER_NAME: ((world-name))
       CLUSTER_ADMIN_PASSWORD: ((cluster-admin-password))
       UAA_ADMIN_CLIENT_SECRET: ((uaa-admin-client-secret))
       NATS_PASSWORD: ((nats-password))
     run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/gcp-cluster-config.sh" ))
  - put: cluster-state
    params:
      repository: state-modified
      merge: true
  - task: init-helm
    config:
      image_resource:
        source:
          repository: eirini/ibmcloud
        type: docker-image
      inputs:
      - name: kube
      - name: ci-resources
      platform: linux
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/init-helm.sh" ))
  - put: cluster-((world-name))-staging-event-ready
    params:
      bump: major
