jobs:
- name: run-tests
  public: true
  plan:
  - in_parallel:
      steps:
      - get: cluster-ci-staging-event-created
        passed:
        - create-cluster-ci
        trigger: true
      - get: eirini
        trigger: true
      - get: eirini-release
      - get: sample-configs
        trigger: true
      - get: golang-lint
        params:
          skip_download: true
        trigger: true
      - get: ci-resources
  - in_parallel:
      steps:
      - file: ci-resources/tasks/run-unit-tests/task.yml
        task: run-unit-tests
      - file: ci-resources/tasks/run-static-checks/task.yml
        task: run-static-checks
      - do:
        - task: download-kubeconfig
          config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: eirini/ibmcloud
              inputs:
              - name:  ci-resources
              outputs:
              - name:  kube
              params:
                CLUSTER_NAME: ((world-name))
                IBMCLOUD_ACCOUNT: ((ibmcloud-account))
                IBMCLOUD_PASSWORD: ((ibmcloud-password))
                IBMCLOUD_USER: ((ibmcloud-user))
              run:
                path: /usr/bin/env
                args:
                - bash
                - -c
                - (( file "../../inline-tasks/download-kubeconfig.sh" ))
        - task: apply-lrp-crd
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: eirini/ibmcloud
            inputs:
            - name:  eirini-release
            - name:  kube
            run:
              path: /usr/bin/env
              args:
              - bash
              - -c
              - (( file "../../inline-tasks/apply-lrp-crd.sh" ))
        - task: run-integration-tests
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: eirini/ci
            inputs:
            - name:  eirini
            - name:  kube
            outputs:
            - name:  output
            run:
              path: /usr/bin/env
              args:
              - bash
              - -c
              - (( file "../../inline-tasks/run-integration-tests.sh" ))

  on_failure: (( grab slack-notification.on_failure ))
