jobs:
- name: run-eats-tests-((gcp-cluster-name))
  public: true
  plan:
  - in_parallel:
      steps:
      - get: lock-ci
        passed:
          - deploy-eirini-yamls-((gcp-cluster-name))
        trigger: true
      - get: eirini
      - get: eirini-release
      - get: ci-resources
  - task: download-kubeconfig
    params:
      CLUSTER_NAME: ((gcp-cluster-name))
      GCP_REGION: ((gcp-region))
      GCP_SERVICE_ACCOUNT_JSON: ((gcp-service-account-json))
      GCP_ZONE: ((gcp-zone))
    config:
      image_resource:
        source:
          repository: google/cloud-sdk
        type: docker-image
      platform: linux
      inputs:
        - name: ci-resources
      outputs:
        - name: kube
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/gcp-download-kubeconfig.sh" ))
  - task: run-eats-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/ci
      inputs:
      - name:  eirini
      - name:  kube
      outputs:
      - name:  output
      params:
          EIRINIUSER_PASSWORD: ((dockerhub-password))
          KUBECONFIG: "kube/config"
          GOOGLE_APPLICATION_CREDENTIALS: "kube/service-account.json"
          HELMLESS_DEPLOYMENT: "true"
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/run-eats-tests.sh" ))
  on_failure: (( grab slack-notification.on_failure ))
