jobs:
- name: run-integration-tests
  public: true
  plan:
  - in_parallel:
      steps:
      - get: eirini
        trigger: true
        passed:
          - run-tests
      - get: ci-resources
  - in_parallel:
      steps:
      - do:
        - task: download-kubeconfig
          config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: google/cloud-sdk
              inputs:
              - name:  ci-resources
              outputs:
              - name:  kube
              params:
                CLUSTER_NAME: (( grab cluster.name ))
                GCP_REGION: ((gcp-region))
                GCP_SERVICE_ACCOUNT_JSON: ((gcp-service-account-json))
                GCP_ZONE: ((gcp-zone))
              run:
                path: /usr/bin/env
                args:
                - bash
                - -c
                - (( file "../../inline-tasks/gcp-download-kubeconfig.sh" ))
        - task: run-integration-tests
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: eirini/ci
            inputs:
            - name:  eirini
            - name:  kube
            outputs:
            - name:  output
            params:
                EIRINIUSER_PASSWORD: ((dockerhub-password))
                GOOGLE_APPLICATION_CREDENTIALS: "kube/service-account.json"
            run:
              path: /usr/bin/env
              args:
              - bash
              - -c
              - (( file "../../inline-tasks/run-integration-tests.sh" ))
  on_failure: (( grab slack-notification.on_failure ))
