jobs:
- name: run-fluentd-unit-tests
  plan:
  - in_parallel:
      steps:
      - get: eirini-fluentd
        trigger: true
  - task: run-unit-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ruby
          username: (( grab config.dockerhub.user ))
          password: (( grab config.dockerhub.password ))
          tag: 2.4
      inputs:
      - name: eirini-fluentd
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/run-fluentd-tests.sh" ))
  on_failure: (( grab slack-notification.on_failure ))
