jobs:
- name: staging-test
  plan:
  - in_parallel:
      steps:
      - get: eirini-staging
        trigger: true
      - get: golang-lint
        params:
          skip_download: true
        trigger: true
      - get: ci-resources
  - in_parallel:
      steps:
      - config:
          image_resource:
            source:
              repository: eirini/ci
            type: docker-image
          inputs:
          - name: eirini-staging
          platform: linux
          run:
            dir: eirini-staging
            path: scripts/test.sh
        task: run-unit-tests
      - file: ci-resources/tasks/run-static-checks/task.yml
        input_mapping:
          eirini: eirini-staging
        task: lint
      - config:
          image_resource:
            source:
              repository: eirini/staging-integration
            type: docker-image
          inputs:
          - name: eirini-staging
          platform: linux
          run:
            dir: eirini-staging
            path: scripts/integration-test.sh
        task: run-integration-test
  on_failure: (( grab slack-notification.on_failure  ))
