jobs:
- name: update-fluentd-version-files
  plan:
  - in_parallel:
      steps:
      - get: eirini-release
      - get: eirini-fluentd
        passed:
        - create-fluentd-docker-image
        trigger: true
      - get: docker-fluentd
        params:
          skip_download: true
        passed:
        - create-fluentd-docker-image
        trigger: true
  - task: update-version-files
    config:
      container_limits: {}
      image_resource:
        source:
          repository: eirini/ci
        type: docker-image
      inputs:
      - name: eirini-fluentd
      - name: eirini-release
      - name: docker-fluentd
      outputs:
      - name: eirini-release-updated
      platform: linux
      params:
        IMAGES: "fluentd"
        COMPONENT_NAME: "fluend"
        COMPONENT_REPO: "eirini-fluentd"
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/update-version-files.sh" ))
  - put: eirini-release
    params:
      repository: eirini-release-updated
  serial: true
  on_failure: (( grab slack-notification.on_failure ))
