jobs:
- name: verify-helm-deployment
  plan:
  - get: ci-resources
  - get: cluster-state
  - get: cluster-ci-staging-event-created
    passed:
    - prepare-cluster-ci
    trigger: true
  - get: eirini-release
    trigger: true
  - task: get-kubeconfig
    file: ci-resources/tasks/download-kubeconfig/task.yml
    params:
      CLUSTER_NAME: ((world-name))
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      IBMCLOUD_USER: ((ibmcloud-user))
  - task: deploy-eirini-bits
    config:
      platform: linux
      image_resource:
        source:
          repository: eirini/ibmcloud
        type: docker-image
      inputs:
      - name: kube
      - name: eirini-release
      - name: cluster-state
      params:
        CLUSTER_NAME: ((world-name))
        NATS_PASSWORD: ((nats-password))
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/deploy-eirini-bits.sh" ))
  - task: verify-deployment
    config:
       platform: linux
       image_resource:
         type: docker-image
         source:
           repository: eirini/ibmcloud
       inputs:
       - name: kube
       run:
         path: /usr/bin/env
         args:
         - bash
         - -c
         - (( file "../../inline-tasks/verify-helm-deployment.sh" ))
  on_failure: (( grab slack-notification.on_failure ))
