---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: eirini/ci
inputs:
- name: docker-fluentd
- name: eirini-release
- name: ci-resources
outputs:
- name: eirini-release-updated
run:
  path: ci-resources/tasks/update-fluentd-digest/task.sh
