---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
- name: ci-resources
- name: gh-pages-pr

params:
  GITHUB_TOKEN:

run:
  path: ci-resources/tasks/check-for-pending-release/task.sh
