---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: eirini/ci
inputs:
- name: docker-opi
- name: docker-opi-init
- name: docker-secret-smuggler
- name: docker-bits-waiter
- name: docker-rootfs-patcher
- name: eirini-release
- name: ci-resources
outputs:
- name: eirini-release-updated
run:
  path: ci-resources/tasks/update-image-digests/task.sh
