resources:
- name: eirini
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini.git
    branch: develop
    paths:
    - fluentd/
- name: eirini-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/eirini-release.git
    branch: fluentd-test
    private_key: ((eirini-release-repo-key))
- name: ci-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci.git
    branch: master
- name: docker-fluentd
  type: docker-image
  source:
    repository: eirini/fluentd
    username: ((dockerhub-user))
    password: ((dockerhub-password))

jobs:
- name: run-unit-tests
  plan:
  - aggregate:
    - get: eirini
      trigger: true
    - get: ci-resources
  - task: run-unit-tests
    file: ci-resources/tasks/run-fluentd-tests/task.yml
- name: update-fluentd-image
  plan:
  - get: eirini
    trigger: true
    passed: [run-unit-tests]
  - get: ci-resources
  - put: docker-fluentd
    params:
      build: eirini/fluentd/
- name: update-fluentd-digest
  plan:
  - get: ci-resources
  - get: eirini-release
  - get: docker-fluentd
    passed: [update-fluentd-image]
    trigger: true
  - task: update-digest
    file: ci-resources/tasks/update-fluentd-digest/task.yml
  - put: eirini-release
    params: {repository: eirini-release-updated}
