---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

inputs:
- name: state
- name: ci-resources

outputs:
- name: configs

run:
  path: ci-resources/tasks/create-eirini-config.yml
