---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

params:
  BOSH2_ENV_ALIAS: lite

inputs:
- name: state
- name: ci-resources

run:
  path: ci-resources/tasks/delete-cf-deployment.sh
