---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

inputs:
- name: ci-resources
- name: eirini-helm-release
- name: configs
- name: state

run:
  path: ci-resources/tasks/helm-install.sh
