---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: diegoteam/eirini

inputs:
- name: eirini
- name: ci-resources

run:
  path: ci-resources/tasks/run-unit-tests.sh
  args:
  - "k8s"
