platform: linux

image_resource:
  type: docker-image
  source:
    repository: flintstonecf/ci

input:
- name: ci-resources
- name: ci-smoke-tests

run:
  path: ci-resources/tasks/run-smoke-tests.sh
     
