---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

params:
  DIRECTOR_NAME: ~
  KUBE_ENDPOINT: ~

inputs:
- name: ci-resources

run:
  path: ci-resources/tasks/run-eirini-smoke-tests.sh
