---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
  - name: bosh-deployment
  - name: 1-click
  - name: ci-resources
  - name: state

params:
  BOSH_LITE_NAME: unconfigured

run:
  path: ci-resources/tasks/update-bosh-dns-config.sh
