---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

params:
  BOSH2_ENV_ALIAS: lite

inputs:
- name: ci-resources
- name: state
- name: manifest

run:
  path: ci-resources/tasks/upload-stemcell.sh
