platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

inputs:
- name: cf-smoke-tests
- name: cf-credentials

params:
  IBMCLOUD_ACCOUNT:
  IBMCLOUD_USER:
  IBMCLOUD_PASSWORD:
  CLUSTER_NAME:

run:
  path: ci-resources/tasks/run-smoke-tests/task.sh
