groups:
- (( merge ))
- name: all
  jobs:
  - (( prepend ))
  - clean-up-environment

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: eirini
  type: pull-request
  check_every: 2h
  webhook_token: ((eirini-pr-webhook-token))
  source:
    repository: akshaymankar/eirini
    access_token: ((github-access-token))
    base_branch: develop

jobs:
  - (( merge ))
  - name: "run-core-cats-eirini-pr"
    plan:
      - (( append ))
      - put: eirini
        params:
          path: eirini
          status: success
  - name: clean-up-environment
    plan:
      - get: eirini
        trigger: true
        passed: ["run-core-cats-eirini-pr"]
      - task: clean-up-environment
        file: ci-resources/tasks/reset-environment/task.yml
        params:
          IBMCLOUD_ACCOUNT: ((ibmcloud-account))
          IBMCLOUD_USER: ((ibmcloud-user))
          IBMCLOUD_PASSWORD: ((ibmcloud-password))
          CLUSTER_NAME: (( grab meta.cluster-name ))
