groups:
- (( merge ))
- name: all
  jobs:
  - (( prepend ))
  - clean-up-environment

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: eirini
  type: pull-request
  check_every: 2h
  webhook_token: ((eirini-pr-webhook-token))
  source:
    repository: mnitchev/eirini
    access_token: ((github-access-token))
    base_branch: develop

jobs:
  - (( merge ))
  - name: "run-core-cats-eirini-pr"
    plan:
      - (( append ))
      - put: eirini
        params:
          path: eirini
          status: success
  - name: clean-up-environment
    plan:
      - get: eirini
      - get: (( concat "cluster-" meta.cluster-name "-staging-event-ready" ))
        passed:
          - (( concat "check-cluster-readiness-" meta.cluster-name ))
      - get: ci-resources
      - put: eirini
        params:
          path: eirini
          status: pending
      - task: clean-up-environment
        file: ci-resources/tasks/nuke-scf/task.yml
        params:
          IBMCLOUD_ACCOUNT: ((ibmcloud-account))
          IBMCLOUD_USER: ((ibmcloud-user))
          IBMCLOUD_PASSWORD: ((ibmcloud-password))
          CLUSTER_NAME: (( grab meta.cluster-name ))
