---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
  - name: ci-resources
  - name: state

params:
  CLUSTER_NAME:
  KUBE_ENDPOINT:

run:
  path: ci-resources/tasks/eirini-smoke-tests/task.sh
