resources:
# - name: every-week
#   icon: alarm
#   type: time
#   source:
#     days:
#     - Wednesday
#     start: 5:00 AM
#     stop: 6:00 AM
- name: ci-resources
  icon: git
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/eirini-ci

jobs:
- name: delete-unused-gcp-disks
  plan:
  # - get: every-week
  #   trigger: true
  - get: ci-resources
  - task: delete-disks
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/gcloud
          username: (( grab config.dockerhub.user ))
          password: (( grab config.dockerhub.password ))
      params:
        GCP_SERVICE_ACCOUNT_JSON: (( grab config.gcp.service-account-json ))
      inputs:
        - name: ci-resources
      run:
        path: bash
        args:
        - -c
        - (( file "../../inline-tasks/delete-unused-gcp-disks.sh" ))
  on_failure: (( grab slack-notification.on_failure ))
