groups:
- name: eirini-ci
  jobs:
  - (( append  ))
  - run-cats-subset

jobs:
- name: run-cats-subset
  plan:
  - get: eirini-release
    passed: [run-smoke-tests]
    trigger: true
  - get: cats
  - get: state
  - get: ci-resources
  - task: run cats
    params:
      .: (( inject cats_conf ))
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: ((cluster-name))
      SKIPPED_TESTS: "Default Environment Variables\
                      |Buildpack cache\
                      |Crashing\
                      |Context Paths\
                      |Multiple App Ports\
                      |A running application\
                      |Buildpacks\
                      |Environment Variables Groups\
                      |An application printing a bunch of output\
                      |Encoding\
                      |Wildcard Routes\
                      |Getting instance information\
                      |Routing Transparency"
    file: ci-resources/tasks/run-cats/task.yml

resources:
- name: cats
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git
