---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

inputs:
- name: ci-resources
- name: eirini-release
- name: deployment-version

run:
  path: ci-resources/tasks/create-docker-images/task.sh
