---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
- name: ci-resources
- name: eirini-release

run:
  path: ci-resources/tasks/create-docker-images/task.sh
