platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

inputs:
- name: repository
- name: ci-resources

outputs:
- name: docker-build-args

run:
  path: ci-resources/tasks/make-docker-build-args/task.sh
