---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
- name: ci-resources

params:
  GITHUB_TOKEN:

run:
  path: ci-resources/tasks/create-github-pr/task.sh
