---
apiVersion: v1
kind: Namespace
metadata:
  name: cf-operator
---
# cf-operator
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cf-operator-psp
  namespace: cf-operator
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - aaa-cf-operator-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-operator-psp
  namespace: cf-operator
roleRef:
  kind: Role
  name: cf-operator-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cf-operator
  namespace: cf-operator
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: aaa-cf-operator-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
    - '*'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  readOnlyRootFilesystem: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
---

# cf-operator-quarks-job
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-operator-quarks-job-psp
  namespace: cf-operator
roleRef:
  kind: Role
  name: cf-operator-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cf-operator-quarks-job
  namespace: cf-operator
