---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eirini-instance-index-env-injector-registrar
  namespace: cf-system
spec:
  podSelector:
    matchLabels:
      job-name: instance-index-env-injector
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
