---
apiVersion: v1
kind: Namespace
metadata:
  name: kubecf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubecf-psp
  namespace: kubecf
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - kubecf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubecf-psp
  namespace: kubecf
roleRef:
  kind: Role
  name: kubecf-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: kubecf
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: kubecf
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  allowedUnsafeSysctls:
  - '*'
  hostIPC: false
  hostNetwork: false
  hostPID: false
  hostPorts:
  - max: 65535
    min: 0
  privileged: true
  fsGroup:
    rule: RunAsAny
  runAsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'

