---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

params:
  IBMCLOUD_ACCOUNT:
  IBMCLOUD_USER:
  IBMCLOUD_PASSWORD:
  CLUSTER_NAME:
  VERSIONING_CLUSTER:

inputs:
- name: ci-resources

run:
  path: ci-resources/tasks/nuke-scf/task.sh
