---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

inputs:
- name: ci-resources
- name: state
- name: eirini-release
- name: release-version

outputs:
- name: release-output

run:
  path: ci-resources/tasks/create-release/task.sh
