jobs:
- name: update-eirini-ci-image
  plan:
  - get: golang-image
    trigger: true
  - get: eirini-ci-image-source
    trigger: true
  - put: eirini-ci-image
    params: {build: eirini-ci-image-source/images/ci}
- name: update-eirini-ibmcloud-image
  plan:
  - get: eirini-ibmcloud-image-source
    trigger: true
  - put: eirini-ibmcloud-image
    params: {build: eirini-ibmcloud-image-source/images/ibmcloud}
- name: update-eirini-scf-builder-image
  plan:
  - get: eirini-scf-builder-image-source
    trigger: true
  - put: eirini-scf-builder-image
    params: {build: eirini-scf-builder-image-source/images/scf-builder}

resources:
- name: eirini-ci-image-source
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci.git
    branch: master
    paths:
    - images/ci/Dockerfile

- name: eirini-ibmcloud-image-source
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci.git
    branch: master
    paths:
    - images/ibmcloud/Dockerfile

- name: eirini-scf-builder-image-source
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci.git
    branch: master
    paths:
    - images/scf-builder/Dockerfile

- name: eirini-ci-image
  type: docker-image
  source:
    repository: eirini/ci
    username: ((docker_hub_user))
    password: ((docker_hub_password))

- name: eirini-ibmcloud-image
  type: docker-image
  source:
    repository: eirini/ibmcloud
    username: ((docker_hub_user))
    password: ((docker_hub_password))

- name: eirini-scf-builder-image
  type: docker-image
  source:
    repository: eirini/scf-builder
    username: ((docker_hub_user))
    password: ((docker_hub_password))

- name: golang-image
  type: docker-image
  source:
    repository: golang
