jobs:
- name: (( concat "deploy-cf-for-k8s-" config.cluster.name ))
  plan:
  - (( prepend ))
  - get: redeploy-timer
    trigger: true
- name: (( concat "smoke-tests-" config.cluster.name ))
  plan:
  - (( prepend ))
  - get: redeploy-timer
    passed:
    - (( concat "deploy-cf-for-k8s-" config.cluster.name ))
    trigger: true
