jobs:
- name: deploy-cf-for-k8s-((world-name))
  plan:
  - (( prepend ))
  - get: redeploy-timer
    trigger: true
- name: smoke-tests-((world-name))
  plan:
  - (( prepend ))
  - get: redeploy-timer
    passed:
    - deploy-cf-for-k8s-((world-name))
    trigger: true
