jobs:
- name: generate-cf-for-k8s-values
  plan:
  - get: cf-for-k8s-github-release
  - get: eirini-release
    trigger: false
- name: deploy-cf-for-k8s-((world-name))
  plan:
  - get: eirini-release
    passed:
    - (( replace ))
    trigger: false
  - get: cf-for-k8s-github-release
  - get: cluster-state
    passed:
    - generate-cf-for-k8s-values
    trigger: true
- name: smoke-tests-((world-name))
  plan:
  - get: cf-for-k8s-github-release
  - get: cluster-state
    passed:
    - deploy-cf-for-k8s-((world-name))
    trigger: true
  - get: eirini-release
    trigger: false
