groups:
- name: eirini-cd
  jobs:
  - (( append ))
  - deploy-cf
  - set-iptable-rules
- name: manage-cf
  jobs:
  - delete-cf-deployment
  - Show CF login summary
- name: manage-director
  jobs: []

jobs:
- name: deploy-cf
  plan:
  - get: state
  - get: ci-resources
  - get: 1-click
  - get: eirini-release
  - get: eirini-release-jobs
    trigger: true
  - get: eirini-source
    trigger: true
    passed: [run-static-checks]
  - get: cf-deployment
    trigger: true
    passed: []
  - get: capi
  - get: ((world_name))-cf-deployment-events
    params: { bump: major }
  - task: create-manifest
    params:
      BOSH_DIRECTOR: ((world_name)).softlayer.com
      DIRECTOR_NAME: ((world_name))
      KUBE_CONF: ((kube_conf))
      KUBE_ENDPOINT: ((kube_endpoint))
      KUBE_NAMESPACE: ((world_name))
      NATS_IP: ((nats_ip))
      USE_EIRINI_RELEASE: ((use_eirini_release))
      ENABLE_OPI_STAGING: ((enable_opi_staging))
      OPI_PORT: ((opi_port))
      REGISTRY_PORT: ((registry_port))
    privileged: true
    file: ci-resources/tasks/create-manifest.yml
  - put: state
    params:
      repository: new-state
  - task: upload-stemcell
    privileged: true
    params:
      BOSH_DIRECTOR: ((world_name)).softlayer.com
      DIRECTOR_NAME: ((world_name))
    file: ci-resources/tasks/upload-stemcell.yml
  - task: deploy
    privileged: true
    params:
      BOSH_DIRECTOR: ((world_name)).softlayer.com
      DIRECTOR_NAME: ((world_name))
      USE_EIRINI_RELEASE: ((use_eirini_release))
    file: ci-resources/tasks/deploy-cf.yml
    on_success:
      put: ((world_name))-cf-deployment-events
      params:
        file: ((world_name))-cf-deployment-events/number

- name: Show CF login summary
  plan:
  - aggregate:
    - get: 1-click
    - get: state
    - get: ((world_name))-cf-deployment-events
      passed: [ deploy-cf ]
      trigger: true
  - task: Show Summary
    file: 1-click/tasks/show-cf-summary.yml
    params:
      BOSH_LITE_NAME: ((world_name))

- name: delete-cf-deployment
  plan:
  - get: ci-resources
  - get: state
  - task: delete
    params:
      DIRECTOR_NAME: ((world_name))
      BOSH_DIRECTOR: ((world_name)).softlayer.com
    file: ci-resources/tasks/delete-cf-deployment.yml

- name: set-iptable-rules
  plan:
  - get: ci-resources
  - get: state
  - get: ((world_name))-cf-deployment-events
    trigger: true
    passed: [deploy-cf]
  - task: set rules
    params:
      DIRECTOR_NAME: ((world_name))
      EIRINI_IP: ((eirini_ip))
    file: ci-resources/tasks/add-iptable-rules.yml

resources:
- name: ci-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci.git
    branch: master

- name: eirini-release-jobs
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
    ignore_paths:
    - src/code.cloudfoundry.org/eirini
    - kube-release

- name: eirini-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))

- name: eirini-source
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
    paths:
    - src/code.cloudfoundry.org/eirini

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment.git
    branch: ((cf-deployment-version))

- name: state
  type: git
  source:
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: master
    private_key: ((github-private-key))

- name: capi
  type: git
  source:
    uri: git@github.com:JulzDiverse/capi-release.git
    branch: ((capi-release-branch))
    private_key: ((capi-key))
