groups:
- name: eirini-cd
  jobs:
  - deploy-eirini-release
- name: manage-cf
  jobs:
  - delete-cf-deployment
- name: manage-director
  jobs: []

jobs:
- name: deploy-eirini-release
  plan:
  - get: state
    passed: []
    trigger: false
  - get: ci-resources
  - get: eirini-release
    trigger: true
  - get: cf-deployment
    trigger: true
  - task: create-manifest
    params:
      BOSH_DIRECTOR: ((bosh_lite_name)).softlayer.com
      DIRECTOR_NAME: ((bosh_lite_name))
      KUBE_CONF: ((kube_conf))
      KUBE_ENDPOINT: ((kube_endpoint))
      KUBE_NAMESPACE: ((bosh_lite_name))
      NATS_IP: ((nats_ip))
      EIRINI_IP: ((eirini_ip))
    privileged: true
    file: ci-resources/tasks/create-manifest.yml
  - put: state
    params:
      repository: new-state
  - task: upload-stemcell
    privileged: true
    params:
      BOSH_DIRECTOR: ((bosh_lite_name)).softlayer.com
      DIRECTOR_NAME: ((bosh_lite_name))
    file: ci-resources/tasks/upload-stemcell.yml
  - task: deploy
    privileged: true
    params:
      BOSH_DIRECTOR: ((bosh_lite_name)).softlayer.com
      DIRECTOR_NAME: ((bosh_lite_name))
    file: ci-resources/tasks/deploy-eirini-release.yml

- name: delete-cf-deployment
  plan:
  - get: ci-resources
  - get: state
  - task: delete
    params:
      DIRECTOR_NAME: ((bosh_lite_name))
      BOSH_DIRECTOR: ((bosh_lite_name)).softlayer.com
    file: ci-resources/tasks/delete-cf-deployment.yml

resources:
- name: ci-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci.git
    branch: master

- name: eirini-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment.git
    branch: ((cf-deployment-version))

- name: state
  type: git
  source:
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: master
    private_key: ((github-private-key))
