groups:
- name: eirini-cd
  jobs:
  - (( append ))
  - run-unit-tests

jobs:
- name: run-unit-tests
  plan:
  - get: ((world_name))-ready-for-deployment-events
    passed: [update-cloud-config-((world_name))]
    trigger: true
  - get: eirini-source
    trigger: true
  - get: ci-resources
  - task: run-tests
    file: ci-resources/tasks/run-unit-tests.yml
