groups:
- name: eirini-ci
  jobs:
  - run-unit-tests

jobs:
- name: run-unit-tests
  plan:
  - get: eirini
    trigger: true
  - get: ci-resources
  - task: run-tests
    file: ci-resources/tasks/run-unit-tests.yml

resources:
- name: eirini
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini.git
    branch: ((eirini-branch))

