groups:
- name: eirini-cd
  jobs:
  - (( append ))
  - run-static-checks

jobs:
- name: run-static-checks
  plan:
  - get: eirini-source
    trigger: true
    passed:
    - run-unit-tests
  - get: ci-resources
  - task: run-static-checks
    file: ci-resources/tasks/run-static-checks.yml
