groups:
- name: eirini-cd
  jobs:
  - (( append ))
  #- create-docker-image
  - deploy-eirini-helm


jobs:
#- name: create-docker-image
  #plan:
  #- get: eirini-release
    #trigger: true
    #passed:
    #- deploy-cf
  #- get: ci-resources
  #- task: create images
    #params:
      #TAG: feature-((eirini-release-branch))
    #file: ci-resources/tasks/create-docker-images.yml

- name: deploy-eirini-helm
  plan:
  - get: eirini-release
    trigger: true
    passed:
    #- create-docker-image
    - deploy-cf
  - get: ci-resources
  - get: state
  - task: create eirini config
    params:
      BOSH_DIRECTOR: ((bosh_lite_name)).softlayer.com
      DIRECTOR_NAME: ((bosh_lite_name))
      KUBE_CONF: ((kube_conf))
      KUBE_ENDPOINT: ((kube_endpoint))
      KUBE_NAMESPACE: ((bosh_lite_name))
      NATS_IP: ((nats_ip))
    file: ci-resources/tasks/create-eirini-config.yml
  - task: deploy
    params:
      USE_EIRINI_RELEASE: ((use_eirini_release))
      KUBE_CONF: ((kube_conf))
      KUBE_ENDPOINT: ((kube_endpoint))
    file: ci-resources/tasks/helm-install.yml
