groups:
- name: eirini-cd
  jobs:
  - (( append ))
  - create-docker-image
  - deploy-eirini-helm

jobs:
- name: create-docker-image
  plan:
  - get: eirini-release
    trigger: true
    passed:
    - deploy-cf
  - task: name
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: /bin/bash
        args:
        - echo
        - "TODO"

- name: deploy-eirini-helm
  plan:
  - get: eirini-release
    trigger: true
    passed:
    - create-docker-image
  - get: state
  - task: create eirini config
    file: ci-resources/tasks/create-eirini-config.yml
  - task: deploy
    file: ci-resources/tasks/helm-install.yml
