groups:
- name: eirini-cd
  jobs:
  - (( append ))
  - create-docker-image
  - deploy-eirini-helm
  - set-iptable-rules

jobs:
- name: create-docker-image
  plan:
  - get: eirini-release
    trigger: true
    passed: []
  - get: capi
    passed: [deploy-cf]
    trigger: true
  - get: ci-resources
  - task: create images
    privileged: true
    params:
      DOCKER_HUB_USER: ((docker_hub_user))
      DOCKER_HUB_PASSWORD: ((docker_hub_password))
      TAG: ((eirini-release-branch))
    file: ci-resources/tasks/create-docker-images.yml

- name: deploy-eirini-helm
  plan:
  - get: eirini-release
    trigger: true
    passed:
    - create-docker-image
  - get: ci-resources
  - get: state
  - task: create eirini config
    params:
      BOSH_DIRECTOR: ((world_name)).softlayer.com
      DIRECTOR_NAME: ((world_name))
      KUBE_CONF: ((kube_conf))
      KUBE_ENDPOINT: ((kube_endpoint))
      KUBE_NAMESPACE: ((world_name))
      NATS_IP: ((nats_ip))
    file: ci-resources/tasks/create-eirini-config.yml
  - task: deploy
    params:
      USE_EIRINI_RELEASE: ((use_eirini_release))
      KUBE_CONF: ((kube_conf))
      DIRECTOR_NAME: ((world_name))
      KUBE_ENDPOINT: ((kube_endpoint))
      KUBE_NAMESPACE: ((world_name))
      TAG: ((eirini-release-branch))
    file: ci-resources/tasks/helm-install.yml
