platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

inputs:
  - name: ci-resources
  - name: cluster-state

outputs:
  - name: state-modified

params:
  CLUSTER_NAME:
  IMAGE_TAG:
  CLUSTER_ADMIN_PASSWORD:
  UAA_ADMIN_CLIENT_SECRET:
  NATS_PASSWORD:
  ENABLE_OPI_STAGING:
  DIEGO_CELL_COUNT:

run:
  path: ci-resources/tasks/gcp-cluster-config/task.sh
