---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/terraform-test

inputs:
  - name: ci-resources

params:
  GCP_SERVICE_ACCOUNT_JSON:
  CLUSTER_NAME:
  WORKER_COUNT:

run:
  path: ci-resources/tasks/gcp-create-cluster/task.sh
