---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
  - name: ci-resources
  - name: worker-info

run:
  path: ci-resources/tasks/curl-app/task.sh
