---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
  - name: ci-resources
  - name: eirinidotcf

outputs:
  - name: db-conf

params:
  CLUSTER_NAME: acceptance
  IBMCLOUD_ACCOUNT:
  IBMCLOUD_USER:
  IBMCLOUD_PASSWORD:

run:
  path: ci-resources/tasks/deploy-eirinidotcf-db/task.sh
