---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
  - name: ci-resources

outputs:
  - name: worker-info

params:
  IBMCLOUD_ACCOUNT:
  IBMCLOUD_USER:
  IBMCLOUD_PASSWORD:
  CLUSTER_NAME:

run:
  path: ci-resources/tasks/deploy-app/task.sh
