#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "NetworkPolicy", "metadata":{"name": "cf-api-server"}})
---
spec:
  ingress:
  #@overlay/match by=overlay.index(0)
  - from:
    #@overlay/match by=overlay.index(0)
    #@overlay/insert before=True
    - podSelector:
        matchLabels:
          name: eirini-task-reporter
      namespaceSelector:
        matchLabels:
          cf-for-k8s.cloudfoundry.org/cf-system-ns: ""
    #@overlay/match by=overlay.index(0)
    #@overlay/insert before=True
    - podSelector:
        matchLabels:
          name: eirini-events
      namespaceSelector:
        matchLabels:
          cf-for-k8s.cloudfoundry.org/cf-system-ns: ""

#@overlay/match by=overlay.subset({"kind": "NetworkPolicy", "metadata":{"name": "eirini-task-reporter"}})
---
spec:
  podSelector:
    matchLabels:
      name: eirini-task-reporter
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eirini-instance-index-env-injector
  namespace: cf-system
spec:
  podSelector:
    matchLabels:
      name: instance-index-env-injector
  egress:
  - {}
  ingress:
  - {}
  policyTypes:
  - Ingress
  - Egress
