---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

inputs:
- name: eirini-release
- name: ci-resources

outputs:
- name: eirini-updated

run:
  path: ci-resources/tasks/init-submodules/task.sh
