---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

inputs:
- name: ci-resources
- name: eirini-release

outputs:
- name: eirini-release-modified

run:
  path: ci-resources/tasks/update-diego-templates/task.sh
