platform: linux

image_resource:
  type: docker-image
  source:
    repository: google/cloud-sdk

inputs:
  - name: ci-resources

outputs:
  - name: kube

params:
  GCP_SERVICE_ACCOUNT_JSON:
  GCP_REGION:
  CLUSTER_NAME:

run:
  path: ci-resources/tasks/gcp-download-kubeconfig/task.sh
