alertmanager:
  persistentVolume:
    enabled: false
server:
  persistentVolume:
    enabled: false
  global:
    scrape_interval: 30s
  extraArgs:
    storage.tsdb.retention.size: 15GB
podSecurityPolicy:
  enabled: true
nodeExporter:
  podSecurityPolicy:
    enabled: true
