---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
- name: ci-resources

params:
  IBMCLOUD_ACCOUNT:
  IBMCLOUD_USER:
  IBMCLOUD_PASSWORD:
  CLUSTER_NAME:

outputs:
- name: ingress

run:
  path: ci-resources/tasks/get-iks-ingress-endpoint/task.sh
