---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

params:
  CONTEXT_PATH: ~
  IMAGE_NAME: ~
  DOCKERFILE_PATH: ~
  CLUSTER_NAME: ~
  DOCKER_HUB_USER: ~
  DOCKER_HUB_PASSWORD: ~

inputs:
  - name: ci-resources
  - name: eirini
  - name: deployment-version

run:
  path: ci-resources/tasks/create-docker-images/task.sh
