---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
- name: kube
- name: ci-resources
- name: eirini-release
- name: state

params:
  CLUSTER_NAME:
  USE_CERT_MANAGER: false

run:
  path: ci-resources/tasks/deploy-scf/task.sh
