---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
- name: kube
- name: ci-resources
- name: eirini-release
- name: state

params:
  IBMCLOUD_ACCOUNT:
  IBMCLOUD_USER:
  IBMCLOUD_PASSWORD:
  CLUSTER_NAME:

run:
  path: ci-resources/tasks/deploy-scf/task.sh
