platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
  - name: ci-resources
  - name: state

outputs:
  - name: state-modified

params:
  IBMCLOUD_ACCOUNT:
  IBMCLOUD_USER:
  IBMCLOUD_PASSWORD:
  CLUSTER_NAME:
  CLUSTER_ADMIN_PASSWORD:
  UAA_ADMIN_CLIENT_SECRET:
  NATS_PASSWORD:

run:
  path: ci-resources/tasks/cluster-config/task.sh
