groups:
- name: fast-forward
  jobs:
  - fast-forward-master
  - fast-forward-master-release

resources:
- name: master
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/eirini.git
    branch: master
    private_key: ((eirini-repo-key))
- name: develop
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini
    branch: develop
- name: release-master
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/eirini-release.git
    branch: master
    private_key: ((eirini-release-repo-key))
- name: release-develop
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release
    branch: develop
- name: ci-no-diego-ready
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: events
    file: ci-no-diego-ready

jobs:
- name: fast-forward-master
  plan:
  - get: ci-no-diego-ready
    trigger: true
  - get: develop
    params:
      submodules: none
  - put: master
    params:
      repository: develop
- name: fast-forward-master-release
  plan:
  - get: ci-no-diego-ready
    trigger: true
    passed:
    - fast-forward-master
  - get: release-develop
    params:
      submodules: none
  - put: release-master
    params:
      repository: release-develop
