platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/gcloud

inputs:
  - name: ci-resources

params:
  GCP_ZONE:
  GCP_SERVICE_ACCOUNT_JSON:
  CLUSTER_NAME:

run:
  path: ci-resources/tasks/gcp-purge-cluster-deployments/task.sh
