groups:
- (( merge ))
- name: all
  jobs:
  - (( prepend ))
  - bump-go-packages
  - merge-bump
- name: test-and-build
  jobs:
  - (( prepend ))
  - bump-go-packages
  - merge-bump
jobs:
- name: bump-go-packages
  plan:
  - in_parallel:
    - get: bump-day
      trigger: true
    - get: eirini-master
      passed: [] # Required for PR pipeline
    - get: ci-resources
  - task: bump-go-packages
    file: ci-resources/tasks/bump-go-packages/task.yml
    input_mapping:
      repository: eirini-master
  - put: eirini
    params:
      force: true
      repository: repository-updated
- name: merge-bump
  plan:
  - get: eirini
    trigger: true
    passed:
    - (( concat "run-core-cats-" meta.cluster-name ))
  - put: eirini-master
    params:
      repository: eirini

resources:
- name: ci-resources
  type: git
  icon: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci
    branch: ((ci-resources-branch))
- name: bump-day
  type: time
  source:
    start: 12:00 AM
    stop: 1:00 AM
    days: [Sunday]
- name: eirini-master
  type: git
  icon: git
  source:
    uri: git@github.com:cloudfoundry-incubator/eirini.git
    branch: master
    private_key: ((eirini-repo-key))
- name: eirini
  type: git
  icon: git
  source:
    uri: git@github.com:cloudfoundry-incubator/eirini.git
    branch: ((eirini-branch))
    private_key: ((eirini-repo-key))
