groups:
- (( merge ))
- name: all
  jobs:
  - (( prepend ))
  - clean-up-environment

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: (( grab meta.pr-repo ))
  type: pull-request
  check_every: 2h
  webhook_token: ((pr-webhook-token))
  source:
    repository: (( concat "cloudfoundry-incubator/" meta.pr-repo ))
    access_token: ((github-access-token))
    base_branch: develop

jobs:
  - name: clean-up-environment
    plan:
      - get: (( grab meta.pr-repo ))
      - get: (( concat "cluster-" meta.cluster-name "-staging-event-ready" ))
        passed:
          - (( concat "check-cluster-readiness-" meta.cluster-name ))
      - get: ci-resources
      - put: (( grab meta.pr-repo ))
        params:
          path: (( grab meta.pr-repo ))
          status: pending
      - task: clean-up-environment
        file: ci-resources/tasks/reset-environment/task.yml
        params:
          IBMCLOUD_ACCOUNT: ((ibmcloud-account))
          IBMCLOUD_USER: ((ibmcloud-user))
          IBMCLOUD_PASSWORD: ((ibmcloud-password))
          CLUSTER_NAME: (( grab meta.cluster-name ))
