groups:
- (( defer merge ))
- name: all
  jobs:
  - (( defer prepend ))
  - (( concat "deploy-scf-uaa-" meta.cluster-name ))
  - (( concat "deploy-scf-eirini-" meta.cluster-name ))
  - (( concat "run-smoke-tests-" meta.cluster-name ))
- name: (( concat "deploy-eirini-" meta.cluster-name ))
  jobs:
  - (( defer prepend ))
  - (( concat "deploy-scf-uaa-" meta.cluster-name ))
  - (( concat "deploy-scf-eirini-" meta.cluster-name ))
  - (( concat "run-smoke-tests-" meta.cluster-name ))

jobs:
- name: (( concat "deploy-scf-uaa-" meta.cluster-name ))
  serial_groups: [ (( grab meta.cluster-name )) ]
  plan:
  - get: eirini-release # Make sure eirini-release is at the top, otherwise the PR pipeline aviator does wrong things
  - get: (( concat "cluster-" meta.cluster-name "-staging-event-ready" ))
    trigger: true
    passed:
    - (( concat "check-cluster-readiness-" meta.cluster-name ))
  - get: scf-uaa-resources
    trigger: true
  - get: ci-resources
  - get: state
  - get: (( concat "cluster-" meta.cluster-name "-staging-event-uaa-ready" ))
    params:
      bump: major
  - task: deploy-uaa
    file: ci-resources/tasks/deploy-uaa/task.yml
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: (( grab meta.cluster-name ))
  - task: waiting-for-uaa
    attempts: 30
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: (( grab meta.cluster-name ))
    file: ci-resources/tasks/waiting-for-uaa/task.yml
  - put: (( concat "cluster-" meta.cluster-name "-staging-event-uaa-ready" ))
    params:
      file: (( concat "cluster-" meta.cluster-name "-staging-event-uaa-ready/number" ))
# lock lives in lock-module
- name: (( concat "deploy-scf-eirini-" meta.cluster-name ))
  serial_groups: [ (( grab meta.cluster-name )) ]
  plan:
  - get: eirini-release
    trigger: true
  - get: ci-resources
  - get: state
  - get: (( concat "cluster-" meta.cluster-name "-staging-event-uaa-ready" ))
    trigger: true
    passed: [(( concat "deploy-scf-uaa-" meta.cluster-name ))]
  - get: (( concat "lock-" meta.cluster-name ))
    trigger: true
    passed: [(( concat "lock-" meta.cluster-name ))]
  - task: deploy-scf
    file: ci-resources/tasks/deploy-scf/task.yml
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: (( grab meta.cluster-name ))
      VERSIONING_CLUSTER: ((world-name))
  - task: smoke-eirini
    attempts: 50
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: (( grab meta.cluster-name ))
    file: ci-resources/tasks/eirini-smoke-tests/task.yml
- name: (( concat "run-smoke-tests-" meta.cluster-name ))
  serial_groups: [ (( grab meta.cluster-name )) ]
  plan:
  - get: eirini-release
    passed: [(( concat "deploy-scf-eirini-" meta.cluster-name ))]
    trigger: true
  - get: (( concat "lock-" meta.cluster-name ))
    trigger: true
    passed: [(( concat "deploy-scf-eirini-" meta.cluster-name ))]
  - get: cf-smoke-tests
  - get: state
  - get: ci-resources
  - task: run smoke tests
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: (( grab meta.cluster-name ))
    file: ci-resources/tasks/run-smoke-tests/task.yml

resources:
- name: ci-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci
    branch: ((ci-resources-branch))
- name: eirini-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
- name: scf-uaa-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
    paths:
    - helm/uaa
- name: (( concat "cluster-" meta.cluster-name "-staging-event-ready" ))
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: events
    file: (( concat meta.cluster-name "-event-ready" ))
    private_key: ((github-private-key))
    initial_version: 0.1.0
- name: (( concat "cluster-" meta.cluster-name "-staging-event-uaa-ready" ))
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: events
    file: (( concat meta.cluster-name "-event-uaa-ready" ))
    private_key: ((github-private-key))
    initial_version: 0.1.0
- name: cf-smoke-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-smoke-tests.git
    branch: master
- name: state
  type: git
  source:
    check_every: 500ms
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: master
    private_key: ((github-private-key))
