groups:
- (( prepend ))
- name: all
  jobs:
  - deploy-scf-uaa-with-diego
  - deploy-scf-eirini-with-diego
  - run-smoke-tests-with-diego

jobs:
- name: deploy-scf-uaa-with-diego
  plan:
  - get: cluster-with-diego-staging-event-ready
    trigger: true
    passed:
    - check-cluster-readiness-with-diego
  - get: scf-uaa-resources
    trigger: true
  - get: ci-resources
  - get: eirini-release
  - get: state
  - get: cluster-with-diego-staging-event-uaa-ready
    params:
      bump: major
  - task: deploy-uaa
    file: ci-resources/tasks/deploy-uaa/task.yml
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: ((cluster-with-diego-staging-name))
  - task: waiting-for-uaa
    attempts: 20
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: ((cluster-with-diego-staging-name))
    file: ci-resources/tasks/waiting-for-uaa/task.yml
  - put: cluster-with-diego-staging-event-uaa-ready
    params:
      file: ((cluster-with-diego-staging-name))-event-uaa-ready/number
- name: deploy-scf-eirini-with-diego
  plan:
  - get: eirini-source
    passed:
    - create-docker-images
  - get: scf-resources
    trigger: true
  - get: ci-resources
  - get: state
  - get: eirini-release
  - get: deployment-version
    trigger: true
    passed:
    - create-docker-images
  - get: cluster-with-diego-staging-event-uaa-ready
    trigger: true
    passed: [deploy-scf-uaa-with-diego]
  - task: deploy-scf
    file: ci-resources/tasks/deploy-scf/task.yml
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: ((cluster-with-diego-staging-name))
      VERSIONING_CLUSTER: ((integration-test-cluster-name))
    on_failure:
      task: purge-namespace
      file: ci-resources/tasks/purge-namespace/task.yml
  - task: smoke-eirini
    attempts: 50
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: ((cluster-with-diego-staging-name))
    file: ci-resources/tasks/eirini-smoke-tests/task.yml
- name: run-smoke-tests-with-diego
  plan:
  - get: eirini-release
    passed: [deploy-scf-eirini-with-diego]
    trigger: true
  - get: cf-smoke-tests
  - get: state
  - get: ci-resources
  - task: run smoke tests
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: ((cluster-with-diego-staging-name))
    file: ci-resources/tasks/run-smoke-tests/task.yml

resources:
- name: ci-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci.git
    branch: ((ci-resources-branch))
- name: eirini-source
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
    paths:
    - src/code.cloudfoundry.org/eirini
    - docker
- name: eirini-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
- name: scf-uaa-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
    paths:
    - helm/uaa
- name: scf-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
    paths:
    - helm/cf
    - helm/eirini
- name: cluster-with-diego-staging-event-ready
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: events
    file: ((cluster-with-diego-staging-name))-event-ready
    private_key: ((github-private-key))
- name: cluster-with-diego-staging-event-uaa-ready
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: events
    file: ((cluster-with-diego-staging-name))-event-uaa-ready
    private_key: ((github-private-key))
- name: cf-smoke-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-smoke-tests.git
    branch: master
- name: deployment-version
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: master
    file: environments/kube-clusters/((integration-test-cluster-name))/deployment-version
    private_key: ((github-private-key))
    initial_version: 1.0.0
- name: state
  type: git
  source:
    check_every: 500ms
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: master
    private_key: ((github-private-key))
