groups:
- (( defer merge ))
- name: all
  jobs:
  - (( defer prepend ))
  - (( concat "create-cluster-" meta.cluster-name ))
  - (( concat "prepare-cluster-" meta.cluster-name ))
  - (( concat "delete-cluster-" meta.cluster-name ))
- name: (( concat "cluster-" meta.cluster-name ))
  jobs:
  - (( concat "create-cluster-" meta.cluster-name ))
  - (( concat "prepare-cluster-" meta.cluster-name ))
  - (( concat "delete-cluster-" meta.cluster-name ))

jobs:
  - name: (( concat "create-cluster-" meta.cluster-name ))
    plan:
    - get: ci-resources
    - get: cluster-state
      trigger: true
      passed: [(( concat "delete-cluster-" meta.cluster-name ))]
    - task: create-kubernetes-cluster
      file: ci-resources/tasks/gcp-create-cluster/task.yml
      params:
        GCP_SERVICE_ACCOUNT_JSON: ((gcp-service-account-json))
        CLUSTER_NAME: (( grab meta.cluster-name ))
        WORKER_COUNT: ((worker_count))
    - put: (( concat "cluster-" meta.cluster-name "-staging-event-created" ))
      params:
        bump: major

  - name: (( concat "prepare-cluster-" meta.cluster-name ))
    plan:
    - get: ci-resources
    - get: (( concat "cluster-" meta.cluster-name "-staging-event-created" ))
      trigger: true
      passed: [(( concat "create-cluster-" meta.cluster-name ))]
    - get: cluster-state
    - task: download-kubeconfig
      file: ci-resources/tasks/gcp-download-kubeconfig/task.yml
      params:
        GCP_SERVICE_ACCOUNT_JSON: ((gcp-service-account-json))
        CLUSTER_NAME: (( grab meta.cluster-name ))
    - task: create-cluster-config
      params:
        CLUSTER_NAME: (( grab meta.cluster-name ))
        CLUSTER_ADMIN_PASSWORD: ((cluster_admin_password))
        UAA_ADMIN_CLIENT_SECRET: ((uaa_admin_client_secret))
        NATS_PASSWORD: ((nats_password))
        ENABLE_OPI_STAGING: (( grab meta.enable-opi-staging ))
        DIEGO_CELL_COUNT: ((diego-cell-count))
      file: ci-resources/tasks/gcp-cluster-config/task.yml
    - put: cluster-state
      params:
        repository: state-modified
        merge: true
    - task: install-helm-dependencies
      params:
        GOOGLE_APPLICATION_CREDENTIALS: "kube/service-account.json"
      file: ci-resources/tasks/install-helm-dependencies/task.yml
    - put: (( concat "cluster-" meta.cluster-name "-staging-event-ready" ))
      params:
        bump: major

  - name: (( concat "delete-cluster-" meta.cluster-name ))
    plan:
    - get: ci-resources
    - task: delete-kubernetes-cluster
      file: ci-resources/tasks/gcp-delete-cluster/task.yml
      params:
        CLUSTER_NAME: (( grab meta.cluster-name ))
        GCP_SERVICE_ACCOUNT_JSON: ((gcp-service-account-json))
    - get: cluster-state
    - task: delete-values-file
      file: ci-resources/tasks/clean-up-cluster-config/task.yml
      params:
        CLUSTER_NAME: (( grab meta.cluster-name ))
    - put: cluster-state
      params:
        merge: true
        repository: state-modified

resources:
  - name: (( concat "cluster-" meta.cluster-name "-staging-event-created" ))
    type: semver
    icon: check-decagram
    source:
      driver: git
      uri: git@github.com:cloudfoundry/eirini-private-config.git
      branch: events
      file: (( concat meta.cluster-name "-event-created" ))
      private_key: ((github-private-key))
      initial_version: 0.1.0
  - name: (( concat "cluster-" meta.cluster-name "-staging-event-ready" ))
    type: semver
    icon: check-decagram
    source:
      driver: git
      uri: git@github.com:cloudfoundry/eirini-private-config.git
      branch: events
      file: (( concat meta.cluster-name "-event-ready" ))
      private_key: ((github-private-key))
      initial_version: 0.1.0
  - name: ci-resources
    type: git
    icon: git
    source:
      uri: https://github.com/cloudfoundry-incubator/eirini-ci
      branch: ((ci-resources-branch))
  - name: cluster-state
    type: git
    icon: folder
    source:
      uri: git@github.com:cloudfoundry/eirini-private-config.git
      branch: master
      private_key: ((github-private-key))
