groups:
- (( merge ))
- name: all
  jobs:
  - (( defer prepend ))
  - helm-lint
jobs:
- name: helm-lint
  plan:
  - get: ci-resources
  - get: eirini-release
    trigger: true
  - task: helm-lint
    file: ci-resources/tasks/helm-lint/task.yml

resources:
- name: ci-resources
  type: git
  icon: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci
    branch: ((ci-resources-branch))
- name: eirini-release
  type: git
  icon: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))

