groups:
- (( defer merge ))
- name: all
  jobs:
  - (( defer prepend ))
  - (( concat "create-cluster-" meta.cluster-name ))
  - (( concat "prepare-cluster-" meta.cluster-name ))
  - (( concat "check-cluster-readiness-" meta.cluster-name ))
  - (( concat "delete-cluster-" meta.cluster-name ))
- name: (( concat "cluster-" meta.cluster-name ))
  jobs:
  - (( concat "create-cluster-" meta.cluster-name ))
  - (( concat "prepare-cluster-" meta.cluster-name ))
  - (( concat "check-cluster-readiness-" meta.cluster-name ))
  - (( concat "delete-cluster-" meta.cluster-name ))

jobs:
  - name: (( concat "create-cluster-" meta.cluster-name ))
    plan:
    - get: ci-resources
    - get: cluster-state
      trigger: true
      passed: [(( concat "delete-cluster-" meta.cluster-name ))]
    - get: (( concat "cluster-" meta.cluster-name "-staging-event-created" ))
      params:
        bump: major
    - task: create-kubernetes-cluster
      file: ci-resources/tasks/create-cluster/task.yml
      params:
        IBMCLOUD_ACCOUNT: ((ibmcloud-account))
        IBMCLOUD_USER: ((ibmcloud-user))
        IBMCLOUD_PASSWORD: ((ibmcloud-password))
        CLUSTER_NAME: (( grab meta.cluster-name ))
        WORKER_COUNT: ((worker_count))
    - put: (( concat "cluster-" meta.cluster-name "-staging-event-created" ))
      params:
        file: (( concat "cluster-" meta.cluster-name "-staging-event-created/number" ))

  - name: (( concat "prepare-cluster-" meta.cluster-name ))
    plan:
    - get: ci-resources
    - get: (( concat "cluster-" meta.cluster-name "-staging-event-created" ))
      trigger: true
      passed: [(( concat "create-cluster-" meta.cluster-name ))]
    - get: cluster-state
    - task: create-cluster-config
      params:
        IBMCLOUD_ACCOUNT: ((ibmcloud-account))
        IBMCLOUD_USER: ((ibmcloud-user))
        IBMCLOUD_PASSWORD: ((ibmcloud-password))
        CLUSTER_NAME: (( grab meta.cluster-name ))
        STORAGE_CLASS: ((storage_class))
        CLUSTER_ADMIN_PASSWORD: ((cluster_admin_password))
        UAA_ADMIN_CLIENT_SECRET: ((uaa_admin_client_secret))
        NATS_PASSWORD: ((nats_password))
        ENABLE_OPI_STAGING: (( grab meta.enable-opi-staging ))
        DIEGO_CELL_COUNT: ((diego-cell-count))
      file: ci-resources/tasks/cluster-config/task.yml
    - put: cluster-state
      params:
        repository: state-modified
        merge: true
    - task: provision-storage
      attempts: 5
      params:
        IBMCLOUD_ACCOUNT: ((ibmcloud-account))
        IBMCLOUD_USER: ((ibmcloud-user))
        IBMCLOUD_PASSWORD: ((ibmcloud-password))
        CLUSTER_NAME: (( grab meta.cluster-name ))
      file: ci-resources/tasks/provision-storage/task.yml
    - task: harden-security
      file: ci-resources/tasks/harden-cluster-security/task.yml
      params:
        IBMCLOUD_ACCOUNT: ((ibmcloud-account))
        IBMCLOUD_USER: ((ibmcloud-user))
        IBMCLOUD_PASSWORD: ((ibmcloud-password))
        CLUSTER_NAME: (( grab meta.cluster-name ))

  - name: (( concat "check-cluster-readiness-" meta.cluster-name ))
    plan:
    - get: ci-resources
    - get: (( concat "cluster-" meta.cluster-name "-staging-event-created" ))
      trigger: true
      passed: [(( concat "prepare-cluster-" meta.cluster-name ))]
    - get: (( concat "cluster-" meta.cluster-name "-staging-event-ready" ))
      params:
        bump: major
    - task: deploy-smoke-test-app
      file: ci-resources/tasks/deploy-app/task.yml
      params:
        IBMCLOUD_ACCOUNT: ((ibmcloud-account))
        IBMCLOUD_USER: ((ibmcloud-user))
        IBMCLOUD_PASSWORD: ((ibmcloud-password))
        CLUSTER_NAME: (( grab meta.cluster-name ))
    - task: check-app-is-up
      attempts: 50
      file: ci-resources/tasks/curl-app/task.yml
    - put: (( concat "cluster-" meta.cluster-name "-staging-event-ready" ))
      params:
        file: (( concat "cluster-" meta.cluster-name "-staging-event-ready/number" ))
  - name: (( concat "delete-cluster-" meta.cluster-name ))
    plan:
    - get: ci-resources
    - task: delete-kubernetes-cluster
      file: ci-resources/tasks/delete-cluster/task.yml
      params:
        IBMCLOUD_ACCOUNT: ((ibmcloud-account))
        IBMCLOUD_USER: ((ibmcloud-user))
        IBMCLOUD_PASSWORD: ((ibmcloud-password))
        CLUSTER_NAME: (( grab meta.cluster-name ))
    - get: cluster-state
    - task: delete-values-file
      file: ci-resources/tasks/clean-up-cluster-config/task.yml
      params:
        CLUSTER_NAME: (( grab meta.cluster-name ))
    - put: cluster-state
      params:
        merge: true
        repository: state-modified

resources:
  - name: (( concat "cluster-" meta.cluster-name "-staging-event-created" ))
    type: semver
    icon: check-decagram
    source:
      driver: git
      uri: git@github.com:cloudfoundry/eirini-private-config.git
      branch: events
      file: (( concat meta.cluster-name "-event-created" ))
      private_key: ((github-private-key))
      initial_version: 0.1.0

  - name: (( concat "cluster-" meta.cluster-name "-staging-event-ready" ))
    type: semver
    icon: check-decagram
    source:
      driver: git
      uri: git@github.com:cloudfoundry/eirini-private-config.git
      branch: events
      file: (( concat meta.cluster-name "-event-ready" ))
      private_key: ((github-private-key))
      initial_version: 0.1.0

  - name: cluster-state
    type: git
    icon: folder
    source:
      uri: git@github.com:cloudfoundry/eirini-private-config.git
      branch: master
      private_key: ((github-private-key))
