groups:
- (( defer merge ))
- name: all
  jobs:
  - (( defer prepend ))
  - (( concat "run-core-cats-" meta.cluster-name ))

jobs:
- name: (( concat "run-core-cats-" meta.cluster-name ))
  serial_groups: [ (( grab meta.cluster-name )) ]
  public: true
  plan:
  - in_parallel:
    - get: cats
    - get: state
    - get: ci-resources
  - task: run cats
    params:
      SKIP_SSL_VALIDATION: true
      USE_HTTP: true
      USE_LOG_CACHE: false
      INCLUDE_APPS: true
      INCLUDE_BACKEND_COMPATIBILITY: false
      INCLUDE_CAPI_EXPERIMENTAL: true
      INCLUDE_CAPI_NO_BRIDGE: true
      INCLUDE_CONTAINER_NETWORKING: true
      INCLUDE_CREDHUB: false
      INCLUDE_DETECT: true
      INCLUDE_DEPLOYMENTS: false
      INCLUDE_DOCKER: true
      INCLUDE_INTERNET_DEPENDENT: true
      INCLUDE_ISOLATION_SEGMENTS: false
      INCLUDE_PRIVATE_DOCKER_REGISTRY: false
      INCLUDE_ROUTE_SERVICES: false
      INCLUDE_ROUTING: true
      INCLUDE_ROUTING_ISOLATION_SEGMENTS: false
      INCLUDE_SECURITY_GROUPS: false
      INCLUDE_SERVICE_DISCOVERY: false
      INCLUDE_SERVICES: false
      INCLUDE_SERVICE_INSTANCE_SHARING: false
      INCLUDE_SSH: false
      INCLUDE_SSO: true
      INCLUDE_TASKS: false
      INCLUDE_V3: false
      INCLUDE_ZIPKIN: true
      NO_OF_TEST_NODES: 16
      CLUSTER_NAME: (( grab meta.cluster-name ))
      SKIPPED_TESTS: (( grab skipped_cats))
    file: ci-resources/tasks/run-cats/task.yml
  - task: download-kubeconfig
    params: (( grab cloud-specific.download-kubeconfig.params ))
    file: (( grab cloud-specific.download-kubeconfig.file ))
  - task: check-leftovers
    file: ci-resources/tasks/check-leftovers/task.yml
  - task: cleanup-blobstore
    file: ci-resources/tasks/cleanup-blobstore/task.yml
    params:
      CLUSTER_NAME: (( grab meta.cluster-name ))
resources:
- name: cats
  type: git
  icon: git
  source:
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git
