groups:
- (( defer merge ))
- name: all
  jobs:
  - (( defer prepend ))
  - (( concat "run-core-cats-" meta.cluster-name ))

jobs:
- name: (( concat "run-core-cats-" meta.cluster-name ))
  plan:
  - get: eirini-release
    passed: [ (( concat "run-smoke-tests-" meta.cluster-name )) ]
    trigger: true
  - get: cats
  - get: state
  - get: ci-resources
  - task: run cats
    params:
      .: (( inject cats_conf ))
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: (( grab meta.cluster-name))
    file: ci-resources/tasks/run-cats/task.yml

resources:
- name: cats
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git
