groups:
- (( merge ))
- name: all
  jobs:
  - (( prepend ))
  - tag-images
- name: test-and-build
  jobs:
  - (( prepend ))
  - tag-images
jobs:
- name: tag-images
  plan:
  - in_parallel:
    - get: eirini
      trigger: true
      passed:
      - create-go-docker-images
      - create-opi-init-docker-image
      - create-secret-smuggler-docker-image
      - create-fluentd-docker-image
    - get: docker-opi
      passed:
      - create-go-docker-images
      params:
        save: true
    - get: docker-opi-init
      passed:
      - create-opi-init-docker-image
      params:
        save: true
    - get: docker-secret-smuggler
      passed:
      - create-secret-smuggler-docker-image
      params:
        save: true
    - get: docker-bits-waiter
      passed:
      - create-go-docker-images
      params:
        save: true
    - get: docker-rootfs-patcher
      passed:
      - create-go-docker-images
      params:
        save: true
    - get: docker-fluentd
      passed:
      - create-fluentd-docker-image
      params:
        save: true
    - put: deployment-version
      params:
        pre: ((world-name))
  - in_parallel:
    - put: docker-opi
      params:
        additional_tags: deployment-version/version
        load: docker-opi
    - put: docker-opi-init
      params:
        additional_tags: deployment-version/version
        load: docker-opi-init
    - put: docker-secret-smuggler
      params:
        additional_tags: deployment-version/version
        load: docker-secret-smuggler
    - put: docker-bits-waiter
      params:
        additional_tags: deployment-version/version
        load: docker-bits-waiter
    - put: docker-rootfs-patcher
      params:
        additional_tags: deployment-version/version
        load: docker-rootfs-patcher
    - put: docker-fluentd
      params:
        additional_tags: deployment-version/version
        load: docker-fluentd
resources:
- name: deployment-version
  type: semver
  source:
    initial_version: 1.0.0
    driver: gcs
    bucket: eirini-ci
    key: image-versions/((world-name))
    json_key: ((gcs-json-key))

