groups:
- (( merge ))
- name: all
  jobs:
  - (( prepend ))
  - run-tests
  - run-static-checks
  - create-docker-images
- name: test-and-build
  jobs:
  - run-tests
  - run-static-checks
  - create-docker-images

jobs:
- name: run-tests
  plan:
  - get: ((integration-test-cluster-name))-event-ready
    trigger: true
    # passed:
    # - check-cluster-readiness
  - get: eirini-source
    trigger: true
  - get: ci-resources
  - task: run-unit-tests
    file: ci-resources/tasks/run-unit-tests/task.yml
  - task: download-kubeconfig
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: ((integration-test-cluster-name))
    file: ci-resources/tasks/download-kubeconfig/task.yml
  - task: run-integration-tests
    file: ci-resources/tasks/run-integration-tests/task.yml
- name: run-static-checks
  plan:
  - get: eirini-source
    trigger: true
    passed:
    - run-tests
  - get: ci-resources
  - task: run-static-checks
    file: ci-resources/tasks/run-static-checks/task.yml
- name: create-docker-images
  plan:
  - get: eirini-source
    trigger: true
    passed:
    - run-static-checks
  - get: ci-resources
  - get: eirini-release
  - get: scf-resources
  - get: deployment-version
    params:
      bump: major
  - task: create images
    privileged: true
    params:
      DOCKER_HUB_USER: ((dockerhub-user))
      DOCKER_HUB_PASSWORD: ((dockerhub-password))
      CLUSTER_NAME: ((integration-test-cluster-name))
    file: ci-resources/tasks/create-docker-images/task.yml
  - put: deployment-version
    params:
      file: deployment-version/version

resources:
- name: ci-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci.git
    branch: ((ci-resources-branch))
- name: eirini-source
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
    paths:
    - src/code.cloudfoundry.org/eirini
    - docker
- name: eirini-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
- name: ((integration-test-cluster-name))-event-ready
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: events
    file: ((integration-test-cluster-name))-event-ready
    private_key: ((github-private-key))
- name: deployment-version
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: master
    file: environments/kube-clusters/((integration-test-cluster-name))/deployment-version
    private_key: ((github-private-key))
    initial_version: 1.0.0
