groups:
- (( defer merge ))
- name: all
  jobs:
  - (( defer prepend ))
  - run-tests
  - create-docker-images
- name: test-and-build
  jobs:
  - run-tests
  - create-docker-images

jobs:
- name: run-tests
  plan:
  - in_parallel:
    - get: (( concat "cluster-" meta.cluster-name "-staging-event-ready" ))
      trigger: true
      passed:
      - (( concat "check-cluster-readiness-" meta.cluster-name ))
    - get: eirini-release
      trigger: true
    - get: eirini
      trigger: true
    - get: ci-resources
    - get: sample-configs
      trigger: true
    - get: deployment-version
  - in_parallel:
    - task: run-unit-tests
      file: ci-resources/tasks/run-unit-tests/task.yml
      input_mapping:
        eirini-source: eirini
    - task: run-static-checks
      file: ci-resources/tasks/run-static-checks/task.yml
      input_mapping:
        eirini-source: eirini
    - task: helm-lint
      file: ci-resources/tasks/helm-lint/task.yml
    - do:
      - task: download-kubeconfig
        params:
          IBMCLOUD_ACCOUNT: ((ibmcloud-account))
          IBMCLOUD_USER: ((ibmcloud-user))
          IBMCLOUD_PASSWORD: ((ibmcloud-password))
          CLUSTER_NAME: (( grab meta.cluster-name ))
        file: ci-resources/tasks/download-kubeconfig/task.yml
      - task: run-integration-tests
        file: ci-resources/tasks/run-integration-tests/task.yml
        input_mapping:
          eirini-source: eirini
- name: create-docker-images
  plan:
  - in_parallel:
    - get: eirini-release
      trigger: true
      passed:
      - run-tests
    - get: eirini
      trigger: true
      passed:
      - run-tests
    - get: ci-resources
    - get: deployment-version
      params:
        bump: major
  - task: make-docker-build-args
    file: ci-resources/tasks/make-docker-build-args/task.yml
  - in_parallel:
    - put: docker-opi
      params:
        build: eirini
        dockerfile: eirini/docker/opi/Dockerfile
        build_args_file: docker-build-args/args.json
    - put: docker-opi-init
      params:
        build: eirini/docker/opi/init
        build_args_file: docker-build-args/args.json
    - put: docker-secret-smuggler
      params:
        build: eirini/docker/registry/certs/smuggler
        build_args_file: docker-build-args/args.json
    - put: docker-bits-waiter
      params:
        build: eirini
        dockerfile: eirini/docker/bits-waiter/Dockerfile
        build_args_file: docker-build-args/args.json
    - put: docker-rootfs-patcher
      params:
        build: eirini
        dockerfile: eirini/docker/rootfs-patcher/Dockerfile
        build_args_file: docker-build-args/args.json
resources:
- name: ci-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci
    branch: ((ci-resources-branch))
- name: sample-configs
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci
    branch: ((ci-resources-branch))
    paths:
    - sample-configs
- name: eirini
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini.git
    branch: ((eirini-branch))
- name: eirini-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
- name: deployment-version
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: master
    file: environments/kube-clusters/((world-name))/deployment-version
    private_key: ((github-private-key))
    initial_version: 1.0.0
- name: docker-opi
  type: docker-image
  source:
    repository: eirini/opi
    username: ((dockerhub-user))
    password: ((dockerhub-password))
- name: docker-opi-init
  type: docker-image
  source:
    repository: eirini/opi-init
    username: ((dockerhub-user))
    password: ((dockerhub-password))
- name: docker-secret-smuggler
  type: docker-image
  source:
    repository: eirini/secret-smuggler
    username: ((dockerhub-user))
    password: ((dockerhub-password))
- name: docker-bits-waiter
  type: docker-image
  source:
    repository: eirini/bits-waiter
    username: ((dockerhub-user))
    password: ((dockerhub-password))
- name: docker-rootfs-patcher
  type: docker-image
  source:
    repository: eirini/rootfs-patcher
    username: ((dockerhub-user))
    password: ((dockerhub-password))
