groups:
- (( defer merge ))
- name: all
  jobs:
  - (( defer prepend ))
  - run-tests
  - create-docker-images
- name: test-and-build
  jobs:
  - run-tests
  - create-docker-images

jobs:
- name: run-tests
  plan:
  - in_parallel:
    - get: (( concat "cluster-" meta.cluster-name "-staging-event-ready" ))
      trigger: true
      passed:
      - (( concat "check-cluster-readiness-" meta.cluster-name ))
    - get: eirini-release
      trigger: true
    - get: eirini
      trigger: true
    - get: ci-resources
    - get: sample-configs
      trigger: true
    - get: deployment-version
  - in_parallel:
    - task: run-unit-tests
      file: ci-resources/tasks/run-unit-tests/task.yml
      input_mapping:
        eirini-source: eirini
    - task: run-static-checks
      file: ci-resources/tasks/run-static-checks/task.yml
      input_mapping:
        eirini-source: eirini
    - task: helm-lint
      file: ci-resources/tasks/helm-lint/task.yml
    - do:
      - task: download-kubeconfig
        params:
          IBMCLOUD_ACCOUNT: ((ibmcloud-account))
          IBMCLOUD_USER: ((ibmcloud-user))
          IBMCLOUD_PASSWORD: ((ibmcloud-password))
          CLUSTER_NAME: (( grab meta.cluster-name ))
        file: ci-resources/tasks/download-kubeconfig/task.yml
      - task: run-integration-tests
        file: ci-resources/tasks/run-integration-tests/task.yml
        input_mapping:
          eirini-source: eirini
- name: create-docker-images
  plan:
  - in_parallel:
    - get: eirini-release
      trigger: true
      passed:
      - run-tests
    - get: eirini
      trigger: true
      passed:
      - run-tests
    - get: ci-resources
    - get: deployment-version
      params:
        bump: major
  - in_parallel:
    - task: build-opi
      privileged: true
      params:
        DOCKER_HUB_USER: ((dockerhub-user))
        DOCKER_HUB_PASSWORD: ((dockerhub-password))
        CLUSTER_NAME: ((world-name))
        CONTEXT_PATH: eirini
        IMAGE_NAME: eirini/opi
        DOCKERFILE_PATH: eirini/docker/opi/Dockerfile
      file: ci-resources/tasks/build-docker-image/task.yml
    - task: build-opi-init
      privileged: true
      params:
        DOCKER_HUB_USER: ((dockerhub-user))
        DOCKER_HUB_PASSWORD: ((dockerhub-password))
        CLUSTER_NAME: ((world-name))
        CONTEXT_PATH: eirini/docker/opi/init
        IMAGE_NAME: eirini/opi-init
        DOCKERFILE_PATH: eirini/docker/opi/init/Dockerfile
      file: ci-resources/tasks/build-docker-image/task.yml
    - task: build-secret-smuggler
      privileged: true
      params:
        DOCKER_HUB_USER: ((dockerhub-user))
        DOCKER_HUB_PASSWORD: ((dockerhub-password))
        CLUSTER_NAME: ((world-name))
        CONTEXT_PATH: eirini/docker/registry/certs/smuggler
        IMAGE_NAME: eirini/secret-smuggler
        DOCKERFILE_PATH: eirini/docker/registry/certs/smuggler/Dockerfile
      file: ci-resources/tasks/build-docker-image/task.yml
    - task: build-bits-waiter
      privileged: true
      params:
        DOCKER_HUB_USER: ((dockerhub-user))
        DOCKER_HUB_PASSWORD: ((dockerhub-password))
        CLUSTER_NAME: ((world-name))
        CONTEXT_PATH: eirini
        IMAGE_NAME: eirini/bits-waiter
        DOCKERFILE_PATH: eirini/docker/bits-watier/Dockerfile
      file: ci-resources/tasks/build-docker-image/task.yml
    - task: build-rootfs-patcher
      privileged: true
      params:
        DOCKER_HUB_USER: ((dockerhub-user))
        DOCKER_HUB_PASSWORD: ((dockerhub-password))
        CLUSTER_NAME: ((world-name))
        CONTEXT_PATH: eirini
        IMAGE_NAME: eirini/rootfs-patcher
        DOCKERFILE_PATH: eirini/docker/rootfs-patcher/Dockerfile
      file: ci-resources/tasks/build-docker-image/task.yml
  - put: deployment-version
    params:
      file: deployment-version/version

resources:
- name: ci-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci
    branch: ((ci-resources-branch))
- name: sample-configs
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci
    branch: ((ci-resources-branch))
    paths:
    - sample-configs
- name: eirini
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini.git
    branch: ((eirini-branch))
- name: eirini-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
- name: deployment-version
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: master
    file: environments/kube-clusters/((world-name))/deployment-version
    private_key: ((github-private-key))
    initial_version: 1.0.0
