groups:
- (( defer merge ))
- name: all
  jobs:
  - (( defer prepend ))
  - update-eirini-version-files
  - update-fluentd-version-files
  - update-secret-smuggler-version-files
  - update-opi-init-version-files
- name: test-and-build
  jobs:
  - (( defer prepend ))
  - update-eirini-version-files
  - update-fluentd-version-files
  - update-secret-smuggler-version-files
  - update-opi-init-version-files
jobs:
- name: update-eirini-version-files
  plan:
  - in_parallel:
    - get: eirini-release
    - get: ci-resources
    - get: eirini
      passed:
      - create-go-docker-images
    - get: docker-opi
      trigger: true
      passed:
      - create-go-docker-images
      params:
        skip_download: true
    - get: docker-bits-waiter
      trigger: true
      passed:
      - create-go-docker-images
      params:
        skip_download: true
    - get: docker-rootfs-patcher
      trigger: true
      passed:
      - create-go-docker-images
      params:
        skip_download: true
  - task: update-version-files
    file: ci-resources/tasks/update-image-digests-new/task.yml
    input_mapping:
      image-code-repository: eirini
      image1: docker-opi
      image2: docker-bits-waiter
      image3: docker-rootfs-patcher
    params:
      IMAGE1_NAME: opi
      IMAGE2_NAME: bits-waiter
      IMAGE3_NAME: rootfs-patcher
      COMPONENT_NAME: Eirini
  - put: eirini-release
    params:
      repository: eirini-release-updated
- name: update-fluentd-version-files
  plan:
  - in_parallel:
    - get: eirini-release
    - get: ci-resources
    - get: eirini-fluentd
      passed:
      - create-fluentd-docker-image
    - get: docker-fluentd
      trigger: true
      passed:
      - create-fluentd-docker-image
      params:
        skip_download: true
  - task: update-version-files
    file: ci-resources/tasks/update-image-digests-new/task.yml
    input_mapping:
      image-code-repository: eirini-fluentd
      image1: docker-fluentd
    params:
      IMAGE1_NAME: fluentd
      COMPONENT_NAME: Fluentd
  - put: eirini-release
    params:
      repository: eirini-release-updated
- name: update-secret-smuggler-version-files
  plan:
  - in_parallel:
    - get: eirini-release
    - get: ci-resources
    - get: eirini-secret-smuggler
      passed:
      - create-secret-smuggler-docker-image
    - get: docker-secret-smuggler
      trigger: true
      passed:
      - create-secret-smuggler-docker-image
      params:
        skip_download: true
  - task: update-version-files
    file: ci-resources/tasks/update-image-digests-new/task.yml
    input_mapping:
      image-code-repository: eirini-secret-smuggler
      image1: docker-secret-smuggler
    params:
      IMAGE1_NAME: secret-smuggler
      COMPONENT_NAME: Secret Smuggler
  - put: eirini-release
    params:
      repository: eirini-release-updated
- name: update-opi-init-version-files
  plan:
  - in_parallel:
    - get: eirini-release
    - get: ci-resources
    - get: eirini-opi-init
      passed:
      - create-opi-init-docker-image
    - get: docker-opi-init
      trigger: true
      passed:
      - create-opi-init-docker-image
      params:
        skip_download: true
  - task: update-version-files
    file: ci-resources/tasks/update-image-digests-new/task.yml
    input_mapping:
      image-code-repository: eirini-opi-init
      image1: docker-opi-init
    params:
      IMAGE1_NAME: opi-init
      COMPONENT_NAME: OPI Init
  - put: eirini-release
    params:
      repository: eirini-release-updated
resources:
- name: eirini-release
  type: git
  icon: git
  source:
    uri: git@github.com:cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
    private_key: ((eirini-release-repo-key))
