groups:
- (( defer merge ))
- name: all
  jobs:
  - (( defer prepend ))
  - update-version-files
- name: test-and-build
  jobs:
  - (( defer prepend ))
  - update-version-files
jobs:
- name: update-version-files
  plan:
  - in_parallel:
    - get: eirini-release
    - get: ci-resources
    - get: docker-opi
      trigger: true
      passed:
        - create-go-docker-images
    - get: docker-opi-init
      trigger: true
      passed:
        - create-opi-init-docker-image
    - get: docker-secret-smuggler
      trigger: true
      passed:
        - create-secret-smuggler-docker-image
    - get: docker-bits-waiter
      trigger: true
      passed:
        - create-go-docker-images
    - get: docker-rootfs-patcher
      trigger: true
      passed:
        - create-go-docker-images
    - get: docker-fluentd
      trigger: true
      passed:
        - create-fluentd-docker-image
  - task: update-image-digests
    file: ci-resources/tasks/update-image-digests/task.yml
  - put: eirini-release
    params: {repository: eirini-release-updated}
resources:
- name: eirini-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
    private_key: ((eirini-release-repo-key))
