---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: koalaman/shellcheck-alpine
    tag: stable

inputs:
- name: ci-resources

run:
  path: ci-resources/tasks/check-shell/task.sh
