jobs:
- name: Keep-CC-up-to-date
  plan:
  - get: ci-resources
  - get: cc-ng-fork
  - get: cc-ng
  - get: capi-ci-passed
    trigger: true
  - task: rebase
    file: ci-resources/tasks/rebase-cc/task.yml
  - put: cc-ng-fork
    params:
      repository: rebased-cc
      force: true
- name: run-CC-tests
  plan:
  - get: cc-ng-fork
    trigger: true
  - get: ci-resources
  - get: eirini-source
    params:
      submodules: all
  - task: run-tests
    file: ci-resources/tasks/run-cc-tests/task.yml
- name: update-submodule-in-capi-release-fork
  plan:
  - get: cc-ng-fork
    passed:
    - run-CC-tests
    trigger: true
  - get: capi-release-fork
    params:
      submodules: none
  - get: ci-resources
  - task: update-cc-submodule
    file: ci-resources/tasks/update-cc-submodule-in-capi-release/task.yml
  - put: capi-release-fork
    params:
      repository: updated-capi-release-fork

resources:
- name: cc-ng-fork
  type: git
  source:
    uri: git@github.com:mnitchev/cloud_controller_ng.git
    branch: eirini
    private_key: ((cc_ng_key))
- name: capi-release-fork
  type: git
  source:
    uri: git@github.com:JulzDiverse/capi-release.git
    branch: develop
    private_key: ((github-private-key))
- name: capi-ci-passed
  type: git
  source:
    uri: git@github.com:cloudfoundry/capi-release.git
    branch: ci-passed
    private_key: ((github-private-key))
- name: cc-ng
  type: git
  source:
    uri: http://github.com/cloudfoundry/cloud_controller_ng.git
    branch: master
- name: ci-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-ci.git
    branch: master
- name: eirini-source
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: master
