---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ci

inputs:
- name: ci-resources
- name: cc-ng-fork
- name: cc-ng
- name: capi-ci-passed

outputs:
- name: rebased-cc

run:
  path: ci-resources/tasks/rebase-cc/task.sh
