apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-issuer
spec:
  acme:
    email: eirini@cloudfoundry.org
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: dns-issuer-staging-account-key
    solvers:
    - dns01:
        clouddns:
          project: cff-eirini-peace-pods
          serviceAccountSecretRef:
            name: dns-account-json
            key: service-account.json
