---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: eirini/ci
inputs:
- name: eirini-release
- name: image-code-repository
- name: image1
- name: image2
  optional: true
- name: image3
  optional: true
- name: ci-resources
outputs:
- name: eirini-release-updated
params:
  IMAGE1_NAME:
  IMAGE2_NAME:
  IMAGE3_NAME:
  COMPONENT_NAME:
run:
  path: ci-resources/tasks/update-image-digests-new/task.sh
