dependencies:
- name: mysql
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 0.15.0
- name: redis
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 6.1.4
