dependencies:
- name: mysql
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 1.6.2
- name: redis
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 10.4.1
